### ISSUE TITLE
您好，有说明里有一句话没明白，肯请您解惑

### ISSUE THREAD

**Issue by liuwaha** [jxxghp/MoviePilot-Plugins#10]
容器首次启动需要下载浏览器内核，根据网络情况可能需要较长时间，此时无法登录。可映射/moviepilot目录避免容器重置后重新触发浏览器内核下载。
上面这句可映射/moviepilot目录，具体是要怎么操作呢？
很喜欢您新的项目，无奈小白，只能依样画葫芦，到这里有点蒙了，不懂操作了。

**Comment by jxxghp** [comment]
看docker启动日志，会自动下载浏览器内核
