### ISSUE TITLE
QB远程操作插件bug： 我未打开限速开关，插件运行的时候自动把QB的限速设为了0

### ISSUE THREAD

**Issue by CookieJaySJ** [jxxghp/MoviePilot-Plugins#104]
这是我的配置界面：
<img width="952" alt="image" src="https://github.com/jxxghp/MoviePilot-Plugins/assets/10297471/d24b1dd5-d653-4656-ac73-a39beade794a">
开始任务的时候会自动执行限速：
<img width="151" alt="image" src="https://github.com/jxxghp/MoviePilot-Plugins/assets/10297471/c973c6ea-7be4-478d-86a8-88e27b0a3436">
@hoey94 @DzAvril

**Comment by DzAvril** [comment]
插件初始化是会检查一下限速开关，进行限速操作。你这里因为还没有配置默认是 0，意思是没有限速，是正常的

**Comment by CookieJaySJ** [comment]
> 插件初始化是会检查一下限速开关，进行限速操作。你这里因为还没有配置默认是 0，意思是没有限速，是正常的

因为我不需要这个插件的限速功能，我需要配合另一个限速插件使用。  所以能不能做到当我没打开限速开关的情况下跳过限速配置？

**Comment by CookieJaySJ** [comment]
> 插件初始化是会检查一下限速开关，进行限速操作。你这里因为还没有配置默认是 0，意思是没有限速，是正常的

因为我没打开限速开关，但插件把我qb本身设置的限速给覆盖了  变成了0

**Comment by hoey94** [comment]
截一下你的配置图。  我看看你的界面是怎么设置的。

**Comment by CookieJaySJ** [comment]
> 截一下你的配置图。 我看看你的界面是怎么设置的。

配置图就在最上面。  其实我想说的就是，在我没打开限速开关的情况下，不要让插件去修改qb本身的限速设置。

**Comment by DzAvril** [comment]
> > 插件初始化是会检查一下限速开关，进行限速操作。你这里因为还没有配置默认是 0，意思是没有限速，是正常的
> 
> 因为我不需要这个插件的限速功能，我需要配合另一个限速插件使用。 所以能不能做到当我没打开限速开关的情况下跳过限速配置？

等我后面修改一下逻辑

**Comment by hoey94** [comment]
大佬，我来帮你修，我提交了个PR，帮我审核一下！ @DzAvril

**Comment by CookieJaySJ** [comment]
> 大佬，我来帮你修，我提交了个PR，帮我审核一下！ @DzAvril

@hoey94 佬，在不打开限速开关的情况下，插件运行能不能不发送 “设置QB限速失败” 这个通知😂。  每次运行一次插件就发一条这个通知有点碍事。  可不可以仅在打开限速开关的情况下再发送限速相关的通知呢？
