### ISSUE TITLE
[BUG] 当插件子目录下存在多个脚本，更新只会更新__init__.py而忽略其他脚本

### ISSUE THREAD

**Issue by HankunYu** [jxxghp/MoviePilot-Plugins#12]
结构比如这样子
<img width="166" alt="image" src="https://github.com/jxxghp/MoviePilot-Plugins/assets/11606969/e8070207-8fbf-493c-a9a5-b91609f580c1">
剩下两个脚本在插件更新时不会更新
希望能更新所有脚本，不然每次都需要重建容器。

**Comment by jxxghp** [comment]
是如何触发插件更新的？

**Comment by HankunYu** [comment]
更新__init__.py版本号以及package.json版本号 commit -> 重启容器手动更新脚本
大佬好 我跟TG上同个人 这个没什么问题了
