### ISSUE TITLE
PR咨询以及刷流插件使用 VDataTableVirual 高分屏渲染卡顿

### ISSUE THREAD

**Issue by InfinityPacer** [jxxghp/MoviePilot-Plugins#122]
- 从VTable切换到VDataTableVirual ，4k 屏幕上出现渲染卡顿，等待响应的问题，1080 下能够正常渲染，本地修改为VDataTable，又出现数据无法渲染的问题，个人对前端比较水，不知道是组件库问题还是前端渲染问题
 - 另外还有一个问题想沟通，看下怎么样一个方案比较合适，个人对刷流插件做了一些扩展
 https://github.com/InfinityPacer/MoviePilot-Plugins
支持了类似站点独立配置，动态删除，定时刷流，数据归档等一些功能，之前一直在个人仓库本地测试，没有提PR，最近功能趋于稳定，加上最近某站点的变更，官方刷流插件也有一些调整，第三方插件如果不关注是不清楚一些逻辑调整的，看这块是否合到官方仓库，如果合的话，是新开一个插件，还是直接合到原有插件，因为部分代码逻辑有较大的重构，以及官方插件有一个功能重叠即离线下载（代理下载种子），所以这块没有把握
- 此外，目前插件不支持版本更新说明，所以还有一些小功能想要迭代，似乎没办法给到用户，只能通过WIKI一些手段来说明，不清楚这块是否有新的想法
- 最后，似乎目前前端没办法支持动态脚本，插件如果希望能够对前端做一些定制都是比较困难，比如前面提到的独立配置，也是通过Dialog变相实现，不知道这块有没有一些思路

VDataTable 数据没有渲染
![PixPin_2024-03-25_21-35-03](https://github.com/jxxghp/MoviePilot-Plugins/assets/160988576/36bbd9e9-d020-4e51-973d-5a806711b4eb)

VDataTableVirual1080 可以正确渲染
![PixPin_2024-03-25_21-40-51](https://github.com/jxxghp/MoviePilot-Plugins/assets/160988576/1b1f1d60-6676-47c9-932b-2ba8cec54f6d)

VDataTableVirual 4k 无法正常渲染
![PixPin_2024-03-25_21-35-40](https://github.com/jxxghp/MoviePilot-Plugins/assets/160988576/9adbe363-31ef-426d-bfab-0d5979fd4f68)

**Comment by jxxghp** [comment]
1、组件有Bug，我也试过了，只能用VDataTableVirual，没测度4K屏的情况。
2、可以合到官方的插件，避免维护两份，合到同一个插件里吧，就以你的为准。
3、目前只能在插件页面通过VAlert组件来添加提示。
4、研究了很久，没搞定。

**Comment by InfinityPacer** [comment]
feature #129
