### ISSUE TITLE
SMTP邮件通知插件在插件市场里的异常显示

### ISSUE THREAD

**Issue by Aqr-K** [jxxghp/MoviePilot-Plugins#157]
我写了个smtp邮件通知插件
更新新版本后，卸载重新安装后发现，插件市场里还是显示这个插件，且插件市场里的下载数显示一千多，安装后显示100多下载量
插件本体功能不受影响，求教一下是为什么？
我尝试过删除数据库重装，本地拉去源码打开moviepilot进行测试两种方法，都无法解决
![Screenshot_20240331_195052_com quark browser](https://github.com/jxxghp/MoviePilot-Plugins/assets/95741669/90cbd3ea-920e-4a15-9078-dcd4796eff63)
![Screenshot_20240331_195048_com quark browser](https://github.com/jxxghp/MoviePilot-Plugins/assets/95741669/10831d0f-c63c-4dff-ad94-2d6e28b40c4f)

**Comment by jxxghp** [comment]
@Aqr-K 你在package.json中的插件名字跟你程度的类名不一致？

**Comment by Aqr-K** [comment]
欧不，我几乎完全重构了一次，没注意到，是不是把类名改回去就正常了？
还有个问题，在编写的时候，我尝试写一个详情页面，然后还没做好，我就先上传了个详情是pass的版本，然后现在安装后，会自动打开空的详情页面，但是这段函数是空的，直接pass掉的，这是什么问题啊，求教一下😨

**Comment by jxxghp** [comment]
@Aqr-K 名字要跟你的类名一致。把注释也删掉
