### ISSUE TITLE
[整理VCB动漫压制组作品] 集数识别错误

### ISSUE THREAD

**Issue by wmbin** [jxxghp/MoviePilot-Plugins#160]
基本一部里面没几个是对的

下面是程序运行的日志

[1.log](https://github.com/jxxghp/MoviePilot-Plugins/files/14816510/1.log)

**Comment by Pixel-LH** [comment]
我看了日志，就一个镜之孤城的结果不对把？（这个也许可以优化），其他的我好像并没看出问题？

**Comment by wmbin** [comment]
> 我看了日志，就一个镜之孤城的结果不对把？（这个也许可以优化），其他的我好像并没看出问题？

镜之孤城电影，出问题都是剧集,可以用关键字 ： 正在转移文件，查看日志

`正在转移文件：/AudioVideo/Downloads/BT/VCB-Studio/[VCB-Studio] Subete ga F ni Naru THE PERFECT INSIDER [Ma10p_1080p]/[VCB-Studio] Subete ga F ni Naru THE PERFECT INSIDER [07][Ma10p_1080p][x265_flac].mkv 到 /AudioVideo/Media/Video/完结动漫/全部成为F -THE PERFECT INSIDER- (2015)/Season 1/全部成为F -THE PERFECT INSIDER- - S01E12 - 第 12 集.mkv`

`正在转移文件：/AudioVideo/Downloads/BT/VCB-Studio/[VCB-Studio] Subete ga F ni Naru THE PERFECT INSIDER [Ma10p_1080p]/[VCB-Studio] Subete ga F ni Naru THE PERFECT INSIDER [03][Ma10p_1080p][x265_flac].mkv 到 /AudioVideo/Media/Video/完结动漫/全部成为F -THE PERFECT INSIDER- (2015)/Season 1/全部成为F -THE PERFECT INSIDER- - S01E11 - 第 11 集.mkv`

**Comment by Pixel-LH** [comment]
> > 我看了日志，就一个镜之孤城的结果不对把？（这个也许可以优化），其他的我好像并没看出问题？
> 
> 镜之孤城电影，出问题都是剧集,可以用关键字 ： 正在转移文件，查看日志 季度错误还好，集数识别错误才蛋疼。。。
> 
> 下面是随便选的2条 第7集 转为了 12集 第3集 转为了 11集
> 
> `正在转移文件：/AudioVideo/Downloads/BT/VCB-Studio/[VCB-Studio] Subete ga F ni Naru THE PERFECT INSIDER [Ma10p_1080p]/[VCB-Studio] Subete ga F ni Naru THE PERFECT INSIDER [07][Ma10p_1080p][x265_flac].mkv 到 /AudioVideo/Media/Video/完结动漫/全部成为F -THE PERFECT INSIDER- (2015)/Season 1/全部成为F -THE PERFECT INSIDER- - S01E12 - 第 12 集.mkv`
> 
> `正在转移文件：/AudioVideo/Downloads/BT/VCB-Studio/[VCB-Studio] Subete ga F ni Naru THE PERFECT INSIDER [Ma10p_1080p]/[VCB-Studio] Subete ga F ni Naru THE PERFECT INSIDER [03][Ma10p_1080p][x265_flac].mkv 到 /AudioVideo/Media/Video/完结动漫/全部成为F -THE PERFECT INSIDER- (2015)/Season 1/全部成为F -THE PERFECT INSIDER- - S01E11 - 第 11 集.mkv`

确实，我没注意到原来是转移出问题了，晚点我去复现排查一下

**Comment by Pixel-LH** [comment]
已修复!
