### ISSUE TITLE
[Question] ChineseSubFinder 插件中的本地路径和远端路径分别是什么

### ISSUE THREAD

**Issue by happyTonakai** [jxxghp/MoviePilot-Plugins#173]
如题，另外设置了这个插件之后，ChineseSubFinder本体还需要配置什么吗？

**Comment by Whichbfj28** [comment]
是不是等同于 ChineseSubFinder的docker配置里面的    volumes:
比如      - /媒体库:/media
这样的话本地路径=/媒体库
远程路径=/media

**Comment by happyTonakai** [comment]
> 是不是等同于 ChineseSubFinder的docker配置里面的 volumes: 比如 - /媒体库:/media 这样的话本地路径=/媒体库 远程路径=/media

不是吧，MP没有`/媒体库`的权限，也只有映射后的权限

https://github.com/jxxghp/MoviePilot-Plugins/blob/8bafa1efce90017ff1ec2d2119a4277b44dfec8b/plugins/chinesesubfinder/__init__.py#L213-L222

local path是MP的地址，remote path是CSF的地址，直接做了字符串的替换。

比如MP的映射是 `/媒体库:/files/media`，CSF的映射是`/媒体库:/media`，那么本地路径就是`/files/media`，远端路径是`/media`。

不知这么设置对不对？

**Comment by Whichbfj28** [comment]
我已经解决了。谢谢大佬给我灵感

**Comment by samzzzz** [comment]
> 我已经解决了。谢谢大佬给我灵感

大佬分享下 最后怎么设置的   是设置下载目录 还是硬链接目录
