### ISSUE TITLE
希望能够将《豆瓣想看》插件里的“想看”和“在看”分离或者自定义

### ISSUE THREAD

**Issue by GlowsSama** [jxxghp/MoviePilot-Plugins#176]
目前《豆瓣想看》插件会同时获取到“想看”和“在看”两个分区下的内容

和house佬的https://github.com/honue/MoviePilot-Plugins《豆瓣书影音档案》插件存在冲突

《豆瓣书影音档案》可以将emby,plex库中的影片反向同步到豆瓣的“在看”和“看过”中

因此媒体库中正在观看的的影片会被《豆瓣书影音档案》同步到豆瓣“在看”  然后《豆瓣想看》又会获取豆瓣“在看”内容给MP添加订阅 导致冲突 重复订阅

**Comment by libukong007** [comment]
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/20178150/678e21a8-d95e-4a47-a3e2-8e2256a915b2)
我的豆瓣想看，没办法同步之前的想看电影，只能同步最新的想看电影，是我哪里设置不对吗？

**Comment by wildbooks** [comment]
目前该插件只支持最新10条想看吗？同步天数设置还有效果吗？

**Comment by SilenceEagle** [comment]
> 目前该插件只支持最新10条想看吗？同步天数设置还有效果吗？

+1
