### ISSUE TITLE
【ChineseSubFinder】使用教程

### ISSUE THREAD

**Issue by Whichbfj28** [jxxghp/MoviePilot-Plugins#183]
因为作者没在插件上详细说明怎么用。估计很多人不知道怎么设置。特别是远程路径什么的

![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/47915665/6a51a0c0-f1be-4c66-901a-1a6a246554e6)
1、在CFS获取api填到插件上。默认服务器地址是http://localhost:19035
2、本地路径=mp的docker内部可以访问到的媒体库位置
3、远程路径=cfs的docker内部可以访问到的媒体库位置
------------------------------
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/47915665/f5e61f07-f78d-43ef-aec3-06333fabafef)
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/47915665/d5b132cf-5978-4d9b-82aa-d47dd7251983)
PS可以理解为：MP内部媒体库路径---硬盘的路径----CFS的内部媒体库路径
----------------------------
对于我的而言就是MP内部（/downloads/媒体库）--硬盘（/storage/opt/downloads/媒体库）----CFS内部（/media）
我的是docker-compose.yml的配置。群晖的请自己研究。

**Comment by msw1990** [comment]
如果是windows那应该两个路径就一样了吧

**Comment by easonlao** [comment]
不知道是不是MP v2不兼容，装了CFS插件设置好，一直没反应

**Comment by zzQ894416361** [comment]
大佬能不能在文件管理那里加上手动下载字幕的按钮

**Comment by tanfeifei2014** [comment]
这个教程真是坑人，全篇都是CFS,找遍全网不知道是什么。应该是CSF吧？？？能不能改一下，不要坑新手啊。

**Comment by alible0drahi** [comment]
多个下载目录只能插件弄分身解决吗
