### ISSUE TITLE
浏览器内核下载失败

### ISSUE THREAD

**Issue by Wood-Fungus** [jxxghp/MoviePilot-Plugins#184]
部署的时候，这个浏览器内核路由开了梯子都下不下来。配置了/moviepilot文件夹，手动下载了chromium-linux.zip，请问手动解压到/moviepilot映射文件夹的目录层级是怎样的，方便截个图嘛谢谢

**Comment by Wood-Fungus** [comment]
2024/4/7 12:26:47  Downloading Chromium 114.0.5735.35 (playwright build v1064)[2m from https://playwright-akamai.azureedge.net/builds/chromium/1064/chromium-linux.zip[22m
2024/4/7 12:26:47  }
2024/4/7 12:26:47    hostname: 'playwright.azureedge.net'
2024/4/7 12:26:47    syscall: 'getaddrinfo',
2024/4/7 12:26:47    code: 'EAI_AGAIN',
2024/4/7 12:26:47    errno: -3001,
2024/4/7 12:26:47      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:internal/dns/promises:95:17) {
2024/4/7 12:26:47  Error: getaddrinfo EAI_AGAIN playwright.azureedge.net
2024/4/7 12:26:27  Downloading Chromium 114.0.5735.35 (playwright build v1064)[2m from https://playwright.azureedge.net/builds/chromium/1064/chromium-linux.zip[22m

**Comment by Propipi666** [comment]
请问是如何解决的？

**Comment by Wood-Fungus** [comment]
> 请问是如何解决的？

太久了，已经忘掉了，不好意思
