### ISSUE TITLE
刷流插件种子大小问题

### ISSUE THREAD

**Issue by 0frostmourne0** [jxxghp/MoviePilot-Plugins#186]
最早的版本中，“种子大小”是可以设置为0.1GB的，插件也能正常扫到种子。
![QQ截图20240407143334](https://github.com/jxxghp/MoviePilot-Plugins/assets/23077424/0d3ebf6b-436e-42c0-a4d9-d466e33baece)

但某个版本更新后好像必须是1GB以上了，小于1会报错无法启动插件。
![QQ截图20240407143353](https://github.com/jxxghp/MoviePilot-Plugins/assets/23077424/ca6b46a6-f757-4493-bfd7-111629ed5848)

希望可以恢复支持，这样可以用来扫小体积种子刷魔力值用，谢谢。

**Comment by InfinityPacer** [comment]
@0frostmourne0 正则有点问题，后面改
