### ISSUE TITLE
清除硬链接1.8版本，对子目录不生效

### ISSUE THREAD

**Issue by wcn666** [jxxghp/MoviePilot-Plugins#191]
监控了/16t，和/link，当/16t/动漫中的文件删除后，/link/动漫中的硬链接不会删除，提示不属于监控范围，不处理。以前的1.2-1.5版本对子目录都是会处理的。想知道是bug还是现在必须精确到子目录。

**Comment by DzAvril** [comment]
请发一下日志截图

**Comment by wcn666** [comment]
好的，这是最新的日志目录，我把子目录加入了也都不生效。以前1.2这些版本都只需要映射大目录就行。
现在我是下载到/16t/保种/国产剧，硬链接到/16t/媒体库/国产剧，然后我删除/16t/保种/国产剧中的源文件后，日志是这样的。
![862529C5-856E-46EF-9B0F-583603280ACE](https://github.com/jxxghp/MoviePilot-Plugins/assets/80608339/abf22cea-6e17-4576-aee3-fc0b62804494)
![0F4A20F3-F6E1-4A0C-9345-7BC3BB224B23](https://github.com/jxxghp/MoviePilot-Plugins/assets/80608339/c132a789-62af-4309-b794-663b53899393)

**Comment by wcn666** [comment]
我是直接把/16t这个文件夹映射给mp，没有跨目录，原来旧版本我是只监控了/16t/保种，/16t/媒体库两个文件夹就能正常工作。

**Comment by DzAvril** [comment]
从日志里看你这个删除的是媒体库在硬链接后通过刮削产生的.jpg和.nfo文件。这些文件在源目录即`/16t/保种`目录里是不存在的。你可以试下删除一个视频文件

**Comment by wcn666** [comment]
但是我确实是通过qb删除了种子文件和源文件，视频文件也删除了，但是硬链接后的视频文件还在。

**Comment by wcn666** [comment]
还有一个就是，我没删除文件的情况下，他也提示我删除了文件，并且把源文件和硬链接以后的目录文件整反了。媒体库的才是硬链接，/16t/保种是原文件。
![32414D61-29D2-4B72-AEAE-553B6E8AC378](https://github.com/jxxghp/MoviePilot-Plugins/assets/80608339/d9afe846-e52f-4fce-b22c-1105afec75c1)

**Comment by wcn666** [comment]
这个豆瓣大包里面的文件，我没有动过，但是他给我删除了，导致我所有大包异常。能不能请问一下您的旧版本怎么降级，我感觉您的旧版本对我就足够用了。

**Comment by wcn666** [comment]
刚才的截图不太完整，我重新提供一下截图，是删除了mp4文件的。
![2C7281C5-FBED-4F13-9F55-C09381E7B067](https://github.com/jxxghp/MoviePilot-Plugins/assets/80608339/e8610954-293c-4657-bfc5-3cdb8b82e2dc)
![C93ED56B-AF68-47E6-BD62-EA5448BF1A4E](https://github.com/jxxghp/MoviePilot-Plugins/assets/80608339/f7c2f810-f428-49bd-8acd-6d60e9fbb34e)
![905F5B8C-6853-46C7-9301-2D39F9D03905](https://github.com/jxxghp/MoviePilot-Plugins/assets/80608339/dfaefb05-2fb2-436d-a4ef-55978bf203f0)

**Comment by DzAvril** [comment]
> 还有一个就是，我没删除文件的情况下，他也提示我删除了文件，并且把源文件和硬链接以后的目录文件整反了。媒体库的才是硬链接，/16t/保种是原文件。 ![32414D61-29D2-4B72-AEAE-553B6E8AC378](https://private-user-images.githubusercontent.com/80608339/321123918-d9afe846-e52f-4fce-b22c-1105afec75c1.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Mjk1MjUsIm5iZiI6MTcxMjcyOTIyNSwicGF0aCI6Ii84MDYwODMzOS8zMjExMjM5MTgtZDlhZmU4NDYtZTUyZi00ZmNlLWIyMmMtMTEwNWFmZWM3NWMxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNjA3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTBjYjdiMjEwOTVmYmRkZDA4N2NjNmI1NTM4NzY3Y2QwOGMxNjczNWYxMjc3M2JmOGI5N2Q2YjU5MWRlYjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.baslmGfDlYjoZcejj-ETlaGn-UXgaMn7ow1VUpT5O2w)

这个问题我也遇到过，按照逻辑这个插件只有在监测到有删除事件时才会去删除硬链接。我当时怀疑是插件【媒体文件同步删除】删除的，卸载这个插件后暂时还没有遇到，你也可以试试。另外你说的源文件硬链接文件反了不用太在意，本身二者互为硬链接，log里简单的把用户删除的记为源文件，插件去找对应的硬链接文件。

**Comment by DzAvril** [comment]
> 这个豆瓣大包里面的文件，我没有动过，但是他给我删除了，导致我所有大包异常。能不能请问一下您的旧版本怎么降级，我感觉您的旧版本对我就足够用了。

看了下完整log，可能确实有隐藏bug，不过我这边很难复现一时也不能修复。mp没有提供直接的降级手段，如果你可以ssh到MP的工作目录下的话，可以试着把低版本的__init__.py文件替换到MP的/app/app/plugins/removelink目录下。不确定是否可行哈。
补充一下，1.8相对于1.6版本只增加了删除空目录的功能，删除硬链接那边的逻辑没有动，不确定降级是否可以规避这个bug

**Comment by wcn666** [comment]
> > 还有一个就是，我没删除文件的情况下，他也提示我删除了文件，并且把源文件和硬链接以后的目录文件整反了。媒体库的才是硬链接，/16t/保种是原文件。 ![32414D61-29D2-4B72-AEAE-553B6E8AC378](https://private-user-images.githubusercontent.com/80608339/321123918-d9afe846-e52f-4fce-b22c-1105afec75c1.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Mjk1MjUsIm5iZiI6MTcxMjcyOTIyNSwicGF0aCI6Ii84MDYwODMzOS8zMjExMjM5MTgtZDlhZmU4NDYtZTUyZi00ZmNlLWIyMmMtMTEwNWFmZWM3NWMxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNjA3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTBjYjdiMjEwOTVmYmRkZDA4N2NjNmI1NTM4NzY3Y2QwOGMxNjczNWYxMjc3M2JmOGI5N2Q2YjU5MWRlYjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.baslmGfDlYjoZcejj-ETlaGn-UXgaMn7ow1VUpT5O2w)
> 
> 这个问题我也遇到过，按照逻辑这个插件只有在监测到有删除事件时才会去删除硬链接。我当时怀疑是插件【媒体文件同步删除】删除的，卸载这个插件后暂时还没有遇到，你也可以试试。另外你说的源文件硬链接文件反了不用太在意，本身二者互为硬链接，log里简单的把用户删除的记为源文件，插件去找对应的硬链接文件。

我没有用这个媒体文件同步删除插件，不过我倒是用了目录监控这个插件，用来实现硬链接，不知道这个会不会引起这个问题。

**Comment by wcn666** [comment]
> > 这个豆瓣大包里面的文件，我没有动过，但是他给我删除了，导致我所有大包异常。能不能请问一下您的旧版本怎么降级，我感觉您的旧版本对我就足够用了。
> 
> 看了下完整log，可能确实有隐藏bug，不过我这边很难复现一时也不能修复。mp没有提供直接的降级手段，如果你可以ssh到MP的工作目录下的话，可以试着把低版本的__init__.py文件替换到MP的/app/app/plugins/removelink目录下。不确定是否可行哈。 补充一下，1.8相对于1.6版本只增加了删除空目录的功能，删除硬链接那边的逻辑没有动，不确定降级是否可以规避这个bug

那我就只有等您修复了。或者您看看方便的话重新上架一个旧版本的。
有个功能不知道能不能实现，删除硬链接，现在不会删除硬链接所在的刮削文件和文件夹，如果能把刮削文件跟所在文件夹一起删除就更好了。

**Comment by wcn666** [comment]
可以把1.6当做稳定版，1.8这种当做测试版，都上架。更新的时候如果能有个更新日志就更好了。

**Comment by DzAvril** [comment]
> > > 还有一个就是，我没删除文件的情况下，他也提示我删除了文件，并且把源文件和硬链接以后的目录文件整反了。媒体库的才是硬链接，/16t/保种是原文件。 ![32414D61-29D2-4B72-AEAE-553B6E8AC378](https://private-user-images.githubusercontent.com/80608339/321123918-d9afe846-e52f-4fce-b22c-1105afec75c1.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Mjk1MjUsIm5iZiI6MTcxMjcyOTIyNSwicGF0aCI6Ii84MDYwODMzOS8zMjExMjM5MTgtZDlhZmU4NDYtZTUyZi00ZmNlLWIyMmMtMTEwNWFmZWM3NWMxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNjA3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTBjYjdiMjEwOTVmYmRkZDA4N2NjNmI1NTM4NzY3Y2QwOGMxNjczNWYxMjc3M2JmOGI5N2Q2YjU5MWRlYjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.baslmGfDlYjoZcejj-ETlaGn-UXgaMn7ow1VUpT5O2w)
> > 
> > 
> > 这个问题我也遇到过，按照逻辑这个插件只有在监测到有删除事件时才会去删除硬链接。我当时怀疑是插件【媒体文件同步删除】删除的，卸载这个插件后暂时还没有遇到，你也可以试试。另外你说的源文件硬链接文件反了不用太在意，本身二者互为硬链接，log里简单的把用户删除的记为源文件，插件去找对应的硬链接文件。
> 
> 我没有用这个媒体文件同步删除插件，不过我倒是用了目录监控这个插件，用来实现硬链接，不知道这个会不会引起这个问题。

这个应该不会

**Comment by DzAvril** [comment]
> > > 这个豆瓣大包里面的文件，我没有动过，但是他给我删除了，导致我所有大包异常。能不能请问一下您的旧版本怎么降级，我感觉您的旧版本对我就足够用了。
> > 
> > 
> > 看了下完整log，可能确实有隐藏bug，不过我这边很难复现一时也不能修复。mp没有提供直接的降级手段，如果你可以ssh到MP的工作目录下的话，可以试着把低版本的__init__.py文件替换到MP的/app/app/plugins/removelink目录下。不确定是否可行哈。 补充一下，1.8相对于1.6版本只增加了删除空目录的功能，删除硬链接那边的逻辑没有动，不确定降级是否可以规避这个bug
> 
> 那我就只有等您修复了。或者您看看方便的话重新上架一个旧版本的。 有个功能不知道能不能实现，删除硬链接，现在不会删除硬链接所在的刮削文件和文件夹，如果能把刮削文件跟所在文件夹一起删除就更好了。

如果能够找到稳定复现的方法修复起来就简单了，你方便的话帮忙试试。
删除刮削文件这个功能，由于我用不上刮削所以去实现这个功能的动力不是很大哈哈。但“将来”肯定会实现的...

**Comment by wcn666** [comment]
> > > > 还有一个就是，我没删除文件的情况下，他也提示我删除了文件，并且把源文件和硬链接以后的目录文件整反了。媒体库的才是硬链接，/16t/保种是原文件。 ![32414D61-29D2-4B72-AEAE-553B6E8AC378](https://private-user-images.githubusercontent.com/80608339/321123918-d9afe846-e52f-4fce-b22c-1105afec75c1.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Mjk1MjUsIm5iZiI6MTcxMjcyOTIyNSwicGF0aCI6Ii84MDYwODMzOS8zMjExMjM5MTgtZDlhZmU4NDYtZTUyZi00ZmNlLWIyMmMtMTEwNWFmZWM3NWMxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNjA3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTBjYjdiMjEwOTVmYmRkZDA4N2NjNmI1NTM4NzY3Y2QwOGMxNjczNWYxMjc3M2JmOGI5N2Q2YjU5MWRlYjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.baslmGfDlYjoZcejj-ETlaGn-UXgaMn7ow1VUpT5O2w)
> > > 
> > > 
> > > 这个问题我也遇到过，按照逻辑这个插件只有在监测到有删除事件时才会去删除硬链接。我当时怀疑是插件【媒体文件同步删除】删除的，卸载这个插件后暂时还没有遇到，你也可以试试。另外你说的源文件硬链接文件反了不用太在意，本身二者互为硬链接，log里简单的把用户删除的记为源文件，插件去找对应的硬链接文件。
> > 
> > 
> > 我没有用这个媒体文件同步删除插件，不过我倒是用了目录监控这个插件，用来实现硬链接，不知道这个会不会引起这个问题。
> 
> 这个应该不会

其他的我没有什么会删除文件的插件了，那就只能是插件自己的问题了。

**Comment by DzAvril** [comment]
> 可以把1.6当做稳定版，1.8这种当做测试版，都上架。更新的时候如果能有个更新日志就更好了。

MP不支持你说的这种测试版、稳定版双版同时存在

**Comment by wcn666** [comment]
> > > > 这个豆瓣大包里面的文件，我没有动过，但是他给我删除了，导致我所有大包异常。能不能请问一下您的旧版本怎么降级，我感觉您的旧版本对我就足够用了。
> > > 
> > > 
> > > 看了下完整log，可能确实有隐藏bug，不过我这边很难复现一时也不能修复。mp没有提供直接的降级手段，如果你可以ssh到MP的工作目录下的话，可以试着把低版本的__init__.py文件替换到MP的/app/app/plugins/removelink目录下。不确定是否可行哈。 补充一下，1.8相对于1.6版本只增加了删除空目录的功能，删除硬链接那边的逻辑没有动，不确定降级是否可以规避这个bug
> > 
> > 
> > 那我就只有等您修复了。或者您看看方便的话重新上架一个旧版本的。 有个功能不知道能不能实现，删除硬链接，现在不会删除硬链接所在的刮削文件和文件夹，如果能把刮削文件跟所在文件夹一起删除就更好了。
> 
> 如果能够找到稳定复现的方法修复起来就简单了，你方便的话帮忙试试。 删除刮削文件这个功能，由于我用不上刮削所以去实现这个功能的动力不是很大哈哈。但“将来”肯定会实现的...

这个发生的时候我看看日志吧。我出现了三四次了

**Comment by DzAvril** [comment]
@wcn666 还是等修复吧，我觉得不是 1.8 版本引入的 bug

**Comment by wcn666** [comment]
> @wcn666 还是等修复吧，我觉得不是 1.8 版本引入的 bug

我3/29号还是正常的，大概4.3-4.4出现了很多次，3.29的时候，还是1.6吗？我好去看对应日志。
方便的话可以加个其他联系方式。

**Comment by DzAvril** [comment]
@wcn666 29 号还是 1.6

**Comment by wcn666** [comment]
> @wcn666 29 号还是 1.6

好吧。等您更新了。

**Comment by wcn666** [comment]
> > > 可以把1.6当做稳定版，1.8这种当做测试版，都上架。更新的时候如果能有个更新日志就更好了。
> > 
> > 
> > MP不支持你说的这种测试版、稳定版双版同时存在
> 
> 我也有存在同样问题, 另外我看插件市场可以同时存在2个不同版本的插件, @wcn666 提到的 同步删除刮削文件,是个不错的功能, 如果能加入这个,这个插件就更强大了...做个开关功能最佳...

可以添加两个版本？如果可以的话，作者愿意添加一个就最好了。

**Comment by wcn666** [comment]
@DzAvril 作者您好，能不能上架一个旧版呀，我今天600+条删除硬链接的消息，一直删除又一直入库，给我包和媒体库全弄乱了。
现在只能停用1.8版本了。

**Comment by DzAvril** [comment]
@wcn666 @tasty007 插件已回退到v1.6，请观察上述问题是否仍然存在。

**Comment by wcn666** [comment]
> @wcn666 @tasty007 插件已回退到v1.6，请观察上述问题是否仍然存在。

好的。我观察一下。

**Comment by wcn666** [comment]
> @wcn666 @tasty007 插件已回退到v1.6，请观察上述问题是否仍然存在。

我看到的插件市场有1.6和1.8 但是我安装1.6 ，插件中心显示出来的还是1.8怎么解决啊

**Comment by DzAvril** [comment]
不清楚，我这边卸载 1.8 再安装 1.6 是正常的在 2024年4月15日，17:02，yxxs ***@***.***> 写道：﻿

@wcn666 @tasty007 插件已回退到v1.6，请观察上述问题是否仍然存在。

我看到的插件市场有1.6和1.8 但是我安装1.6 ，插件中心显示出来的还是1.8怎么解决啊

**Comment by wcn666** [comment]
> 不清楚，我这边卸载 1.8 再安装 1.6 是正常的在 2024年4月15日，17:02，yxxs ***@***.***> 写道：﻿ @wcn666 @tasty007 插件已回退到v1.6，请观察上述问题是否仍然存在。 我看到的插件市场有1.6和1.8 但是我安装1.6 ，插件中心显示出来的还是1.8怎么解决啊 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

好的 我再试一下  。1.6版本这个是只需要监控父目录 子目录会自动加入监控对吧

**Comment by DzAvril** [comment]
@wcn666 是的

**Comment by wcn666** [comment]
> @wcn666 是的

ok。我重启了mp现在下载到了1.6，测试几天给您回复情况。

**Comment by wcn666** [comment]
@DzAvril 【INFO】2024-04-15 22:02:53,769 - removelink - 监控目录：['/disk/下载', '/disk/媒体库', '/16t/下载', '/16t/bt', '/16t/保种', '/16t/媒体库']
【INFO】2024-04-15 22:02:53,761 - removelink - Hello, RemoveLink! config {'enabled': True, 'notify': True, 'onlyonce': False, 'monitor_dirs': '/disk/下载\n/disk/媒体库\n/16t/下载\n/16t/bt\n/16t/保种\n/16t/媒体库', 'exclude_keywords': '', 'undefined': True, 'exclude_dirs': '/disk/下载\n/16t/下载\n/16t/bt\n/16t/保种'}

请问这个日志是什么意思啊

**Comment by wcn666** [comment]
哦哦 我还以为是报错信息

**Comment by DzAvril** [comment]
> > @wcn666 输出配置信息，没啥意思
> 
> 请问如何清理掉插件的日志缓存啊 ？重置插件，卸载重装插件之前的缓存日志都还在

不清楚，得问MP作者大大

**Comment by wcn666** [comment]
> @wcn666 是的

1.6版本对子目录貌似不监控？

这是日志信息 

【INFO】2024-04-16 19:05:21,902 - removelink - 文件 /16t/保种/国产剧/斗破苍穹之少年归来.Battle.Through.The.Heaven.S02.2023.2160p.WEB-DL.H265.AAC-HDKylinWeb/斗破苍穹之少年归来.Battle.Through.The.Heaven.S02E14.2023.2160p.WEB-DL.H265.AAC-HDKylinWeb.mp4 未在监控列表中，不处理
【INFO】2024-04-16 19:05:21,901 - removelink - 监测到删除文件：/16t/保种/国产剧/斗破苍穹之少年归来.Battle.Through.The.Heaven.S02.2023.2160p.WEB-DL.H265.AAC-HDKylinWeb/斗破苍穹之少年归来.Battle.Through.The.Heaven.S02E14.2023.2160p.WEB-DL.H265.AAC-HDKylinWeb.mp4
【INFO】2024-04-16 19:05:21,901 - removelink - 文件 /16t/保种/国产剧/斗破苍穹之少年归来.Battle.Through.The.Heaven.S02.2023.2160p.WEB-DL.H265.AAC-HDKylinWeb/斗破苍穹之少年归来.Battle.Through.The.Heaven.S02E13.2023.2160p.WEB-DL.H265.AAC-HDKylinWeb.mp4 未在监控列表中，不处理
【INFO】2024-04-16 19:05:21,900 - removelink - 监测到删除文件：/16t/保种/国产剧/斗破苍穹之少年归来.Battle.Through.The.Heaven.S02.2023.2160p.WEB-DL.H265.AAC-HDKylinWeb/斗破苍穹之少年归来.Battle.Through.The.Heaven.S02E13.2023.2160p.WEB-DL.H265.AAC-HDKylinWeb.mp4

这是我的目录监控设置 
监控目录
/16t/保种
/16t/媒体库

请问是我设置有问题嘛？

**Comment by wcn666** [comment]
@DzAvril 之前的版本我这样设置是可以删除的  具体哪一个版本不太记得了  莫不是我设置不对

**Comment by DzAvril** [comment]
> @DzAvril 之前的版本我这样设置是可以删除的 具体哪一个版本不太记得了 莫不是我设置不对

1. 所有版本都是会监控子目录的。

2 . 你删除的文件是在启动插件之前添加的还是在启动插件之后添加的？

3. 可以试下重启插件，再找个子目录里的文件删除测试下 （避免影响做种，最好ssh上去手动添加文件再硬链接测试）

4. #124 报的问题是在插件启动后添加的文件，删除源文件不会触发删除硬链接，确认下是否和这个问题一样？他报的这个我没有复现

**Comment by wcn666** [comment]
> > @DzAvril 之前的版本我这样设置是可以删除的 具体哪一个版本不太记得了 莫不是我设置不对
> 
> 1. 所有版本都是会监控子目录的。
> 
> 2 . 你删除的文件是在启动插件之前添加的还是在启动插件之后添加的？
> 
> 3. 可以试下重启插件，再找个子目录里的文件删除测试下 （避免影响做种，最好ssh上去手动添加文件再硬链接测试）
> 4. [removelink 对于新增监控文件处理有问题 #124](https://github.com/jxxghp/MoviePilot-Plugins/issues/124) 报的问题是在插件启动后添加的文件，删除源文件不会触发删除硬链接，确认下是否和这个问题一样？他报的这个我没有复现

好的。我删除的文件是启动后添加的。
我去试一下他的这个我能不能复显。

**Comment by DzAvril** [comment]
如果是启动后添加的，看下日志里有没有这个文件添加的记录。在 2024年4月16日，19:42，yxxs ***@***.***> 写道：﻿


@DzAvril 之前的版本我这样设置是可以删除的 具体哪一个版本不太记得了 莫不是我设置不对


所有版本都是会监控子目录的。

2 . 你删除的文件是在启动插件之前添加的还是在启动插件之后添加的？

可以试下重启插件，再找个子目录里的文件删除测试下 （避免影响做种，最好ssh上去手动添加文件再硬链接测试）
removelink 对于新增监控文件处理有问题 #124 报的问题是在插件启动后添加的文件，删除源文件不会触发删除硬链接，确认下是否和这个问题一样？他报的这个我没有复现


好的。我删除的文件是启动后添加的。
我去试一下他的这个我能不能复显。

**Comment by wcn666** [comment]
有这个文件添加的记录的。还有就是，方便给个电报联系方式吗？或者其他也行，感觉这个沟通不太方便。

INFO】2024-04-16 19:14:52,304 - removelink - 监测到新增文件：/16t/媒体库/国产剧/斗破苍穹之少年归来 (2023)/Season 2/斗破苍穹之少年归来 - S02E14 - 第 14 集.mp4
【INFO】2024-04-16 19:14:49,741 - removelink - 监测到新增文件：/16t/媒体库/国产剧/斗破苍穹之少年归来 (2023)/poster.jpg
【INFO】2024-04-16 19:14:49,598 - removelink - 监测到新增文件：/16t/媒体库/国产剧/斗破苍穹之少年归来 (2023)/backdrop.jpg
【INFO】2024-04-16 19:14:49,495 - removelink - 监测到新增文件：/16t/媒体库/国产剧/斗破苍穹之少年归来 (2023)/tvshow.nfo
【INFO】2024-04-16 19:14:49,458 - removelink - 监测到新增文件：/16t/媒体库/国产剧/斗破苍穹之少年归来 (2023)/Season 2/斗破苍穹之少年归来 - S02E13 - 第 13 集.mp4
【INFO】2024-04-16 19:14:49,457 - removelink - 监测到新增文件：/16t/媒体库/国产剧/斗破苍穹之少年归来 (2023)/Season 2/斗破苍穹之少年归来 - S02E13 - 第 13 集.mp4
【INFO】2024-04-16 19:10:47,661 - removelink - 更新文件列表完成，共计52960个文件，耗时：1.9951462745666504秒

**Comment by wcn666** [comment]
@DzAvril 我测试的结果跟他差不多，不同的是
脚本运行后 ，添加的文件，无论是我删除源文件，还是硬链接，都无法删除另一边
相同的是，脚本运行之前添加的文件，或者添加文件后重启插件，此时删除源文件，可以同步删除硬链接

【清理硬链接】
监控到删除源文件：/16t/保种/国产剧/斗破苍穹之少年归来.Battle.Through.The.Heaven.S02.2023.2160p.WEB-DL.H265.AAC-HDKylinWeb/斗破苍穹之少年归来.Battle.Through.The.Heaven.S02E13.2023.2160p.WEB-DL.H265.AAC-HDKylinWeb.mp4
同步删除硬链接文件：/16t/媒体库/国产剧/斗破苍穹之少年归来 (2023)/Season 2/斗破苍穹之少年归来 - S02E13 - 第 13 集.mp4

**Comment by wcn666** [comment]
如果我重启插件以后删除媒体库，倒是会删除硬链接。

**Comment by wcn666** [comment]
> > 有这个文件添加的记录的。还有就是，方便给个电报联系方式吗？或者其他也行，感觉这个沟通不太方便。
> > INFO】2024-04-16 19:14:52,304 - removelink - 监测到新增文件：/16t/媒体库/国产剧/斗破苍穹之少年归来 (2023)/Season 2/斗破苍穹之少年归来 - S02E14 - 第 14 集.mp4 【INFO】2024-04-16 19:14:49,741 - removelink - 监测到新增文件：/16t/媒体库/国产剧/斗破苍穹之少年归来 (2023)/poster.jpg 【INFO】2024-04-16 19:14:49,598 - removelink - 监测到新增文件：/16t/媒体库/国产剧/斗破苍穹之少年归来 (2023)/backdrop.jpg 【INFO】2024-04-16 19:14:49,495 - removelink - 监测到新增文件：/16t/媒体库/国产剧/斗破苍穹之少年归来 (2023)/tvshow.nfo 【INFO】2024-04-16 19:14:49,458 - removelink - 监测到新增文件：/16t/媒体库/国产剧/斗破苍穹之少年归来 (2023)/Season 2/斗破苍穹之少年归来 - S02E13 - 第 13 集.mp4 【INFO】2024-04-16 19:14:49,457 - removelink - 监测到新增文件：/16t/媒体库/国产剧/斗破苍穹之少年归来 (2023)/Season 2/斗破苍穹之少年归来 - S02E13 - 第 13 集.mp4 【INFO】2024-04-16 19:10:47,661 - removelink - 更新文件列表完成，共计52960个文件，耗时：1.9951462745666504秒
> 
> 看起来只是刮削过的文件检测到了，原始下载的文件没有监控到。你做个测试，插件运行时在你/16t/保种目录下创建新的文件看下插件日志有没有检测到。
> 
> P.S. 我平时时间也不多，加TG可能也就抽空看一下，和这里没啥区别。觉得有必要的话在MP的交流群里发一个12345，我看到了加你

运行的时候创建新的文件，插件检测到了。
群里已发。

**Comment by DzAvril** [comment]
@wcn666 找到原因了，更新到了1.7，再试试看
