### ISSUE TITLE
关于硬连接这块的效率

### ISSUE THREAD

**Issue by 4bookmark** [jxxghp/MoviePilot-Plugins#206]
我概念中的硬连接 难道不是应该是 快速复制一个快捷方式这样的么？
为什么 会像复制文件的几百m 几百m的 扩建成一个文件
效率很低
这里有款的硬连接的github 感觉可以参考
而且他在针对 单视频文件（有的种子 是单视频文件 不带文件夹的）的时候 还能生成一层文件夹 方便管理
这样在进行刮削的时候 会更加合理

https://github.com/likun7981/hlink

希望这个repo可以启发到。

**Comment by jxxghp** [comment]
你跨盘变成复制了吧。项目这么久了，怎么会有这种基础性问题？
先研究清楚基本的东西再提建议。
