### ISSUE TITLE
站点刷流插件建议增加删种执行开关

### ISSUE THREAD

**Issue by sq8422779** [jxxghp/MoviePilot-Plugins#207]
在没有设置任何删种策略时，插件仍然会执行删种检查,会有很多无效的工作，排版也建议优化一下，有个下载规则个删除规则中间最好有个分割线
配置页面
![屏幕截图 2024-04-14 140408](https://github.com/jxxghp/MoviePilot-Plugins/assets/130560671/66ff5ba7-127d-4ad7-af3f-97ac7e56565d)

**Comment by InfinityPacer** [comment]
@sq8422779 Check服务，不仅仅是删除种子，还有很多其他的功能，这样一个99.9%都会打开开关的功能没有价值，反而徒增工作量
