### ISSUE TITLE
“清理硬链接”插件无法清除“短剧刮削”插件所创建的硬链接

### ISSUE THREAD

**Issue by LoSiTeE** [jxxghp/MoviePilot-Plugins#212]
使用"短剧刮削"插件硬链接的文件无法被正确删除。
短剧刮削插件的设置如图：
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/125968595/512fbf2f-141b-4ead-8f6a-f0058048c549)
清理硬链接插件的设置如图：
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/125968595/456fbcef-d4d5-4573-a2ea-c7d6642033d7)

已经确认短剧刮削插件硬链接的文件跟源文件的inode id是一致的。查看清理硬链接插件的日志如图：
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/125968595/861442e1-5831-48fa-a4e0-8dffb7120fcf)
插件只检测到文件被删除，但没有删除对应的源文件。

@DzAvril 麻烦看一下，谢谢啦

**Comment by DzAvril** [comment]
更新了v1.7，请试试这个版本问题还存在不

**Comment by LoSiTeE** [comment]
> 更新了v1.7，请试试这个版本问题还存在不

你好，目前插件版本为1.8。问题依旧…
查看了下日志，日志监控到了“/watching/mediarepo/短剧”新增的硬连接文件，也监控到了他们被删除。但跟“/watching/短剧”目录下的源文件相关的信息一条也没有，包括新增，和删除日志里都没有相关信息。

**Comment by LoSiTeE** [comment]
> 更新了v1.7，请试试这个版本问题还存在不

经由媒体库删除硬连接文件无法成功触发源文件的同步删除

**Comment by DzAvril** [comment]
> > 更新了v1.7，请试试这个版本问题还存在不
> 
> 你好，目前插件版本为1.8。问题依旧… 查看了下日志，日志监控到了“/watching/mediarepo/短剧”新增的硬连接文件，也监控到了他们被删除。但跟“/watching/短剧”目录下的源文件相关的信息一条也没有，包括新增，和删除日志里都没有相关信息。

卸载当前1.8版本，插件市场有个1.7版本，用这个试试。

p.s. 你在用的1.8版本之前有用户反馈随机删除文件，回退到1.6版本了

**Comment by LoSiTeE** [comment]
> > > 更新了v1.7，请试试这个版本问题还存在不
> > 
> > 
> > 你好，目前插件版本为1.8。问题依旧… 查看了下日志，日志监控到了“/watching/mediarepo/短剧”新增的硬连接文件，也监控到了他们被删除。但跟“/watching/短剧”目录下的源文件相关的信息一条也没有，包括新增，和删除日志里都没有相关信息。
> 
> 卸载当前1.8版本，插件市场有个1.7版本，用这个试试。
> 
> p.s. 你在用的1.8版本之前有用户反馈随机删除文件，回退到1.6版本了

老哥，插件安装出了问题……我用这个插件卸载了1.8版本
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/125968595/809b5791-59d6-4f3f-8daa-56a5266c4d01)
然后去安装1.7版本，但是我重启moviepilot，1.7版本插件就会消失。

具体的现象如下，且会不断重复：

安装1.7版本插件，商店列表里显示只有1.7版本，安装，第一次会提示安装成功，但插件列表里是空的。然后再进商店，这时候商店会显示两个版本，一个1.7，一个1.8。再安装1.7，这时候插件列表里会显示1.7版本。但商店里1.7版本消失，1.8版本还在。然后重启moviepilot，会回到最开始的状态，1.7版本插件消失，商店里有1.7版本，没有1.8版本，一切重新回到开始的状态。

**Comment by LoSiTeE** [comment]
> @LoSiTeE 没用这个卸载过不太清楚咋回事😂

不懂为什么有这种情况。这次我安装1.7版本之后没有重启，使用EMBY删除媒体库文件还是有这个问题。另外我尝试了删除由“实时硬连接”插件创建的硬链接文件，测试一切正常。

**Comment by LoSiTeE** [comment]
> > @LoSiTeE 没用这个卸载过不太清楚咋回事😂
> 
> 不懂为什么有这种情况。这次我安装1.7版本之后没有重启，使用EMBY删除媒体库文件还是有这个问题。另外我尝试了删除由“实时硬连接”插件创建的硬链接文件，测试一切正常。



> @LoSiTeE 没用这个卸载过不太清楚咋回事😂

emmm，1.7还是有问题，硬链接实现方式有很多种吗？为啥"实时硬链接"插件硬链的文件好用，换成“短剧刮削”插件就不行…

**Comment by DzAvril** [comment]
> > > @LoSiTeE 没用这个卸载过不太清楚咋回事😂
> > 
> > 
> > 不懂为什么有这种情况。这次我安装1.7版本之后没有重启，使用EMBY删除媒体库文件还是有这个问题。另外我尝试了删除由“实时硬连接”插件创建的硬链接文件，测试一切正常。
> 
> > @LoSiTeE 没用这个卸载过不太清楚咋回事😂
> 
> emmm，1.7还是有问题，硬链接实现方式有很多种吗？为啥"实时硬链接"插件硬链的文件好用，换成“短剧刮削”插件就不行…

只有一种硬链接方式，重启插件后能删除硬链接吗？

**Comment by LoSiTeE** [comment]
> > > > @LoSiTeE 没用这个卸载过不太清楚咋回事😂
> > > 
> > > 
> > > 不懂为什么有这种情况。这次我安装1.7版本之后没有重启，使用EMBY删除媒体库文件还是有这个问题。另外我尝试了删除由“实时硬连接”插件创建的硬链接文件，测试一切正常。
> > 
> > 
> > > @LoSiTeE 没用这个卸载过不太清楚咋回事😂
> > 
> > 
> > emmm，1.7还是有问题，硬链接实现方式有很多种吗？为啥"实时硬链接"插件硬链的文件好用，换成“短剧刮削”插件就不行…
> 
> 只有一种硬链接方式，重启插件后能删除硬链接吗？

插件如何重启？

**Comment by DzAvril** [comment]
@LoSiTeE “启用插件”开关关闭再打开

**Comment by LoSiTeE** [comment]
> @LoSiTeE “启用插件”开关关闭再打开

还是这个问题，没有改善

**Comment by LoSiTeE** [comment]
> @LoSiTeE “启用插件”开关关闭再打开

我打算这两天重新装一下moviepilot，如果还有问题我再来反馈一下

**Comment by DzAvril** [comment]
> > @LoSiTeE “启用插件”开关关闭再打开
> 
> 我打算这两天重新装一下moviepilot，如果还有问题我再来反馈一下

有没有使用短剧自动分类插件？用这个插件时，“清理硬链接”插件会把源文件删掉

**Comment by LoSiTeE** [comment]
> > > @LoSiTeE “启用插件”开关关闭再打开
> > 
> > 
> > 我打算这两天重新装一下moviepilot，如果还有问题我再来反馈一下
> 
> 有没有使用短剧自动分类插件？用这个插件时，“清理硬链接”插件会把源文件删掉

🤨这样的吗？我是之前用短剧分类插件的，但是老莫名其妙出问题，后来才改成这个用短剧刮削插件的。但是依旧有问题😐

请问我用短剧分类插件的话，如果清理硬链接里面没有填写对应的短剧目录，只是监控了其他目录的话，也会删除短剧的源文件吗？

**Comment by DzAvril** [comment]
> > > > @LoSiTeE “启用插件”开关关闭再打开
> > > 
> > > 
> > > 我打算这两天重新装一下moviepilot，如果还有问题我再来反馈一下
> > 
> > 
> > 有没有使用短剧自动分类插件？用这个插件时，“清理硬链接”插件会把源文件删掉
> 
> 🤨这样的吗？我是之前用短剧分类插件的，但是老莫名其妙出问题，导致短剧无法被自动分类。后来改成用短剧刮削插件。但是清除硬链接又无法正常工作😐
> 
> 请问我用短剧分类插件的话，如果清理硬链接里面没有填写对应的短剧目录，只是监控了其他目录的话，也会删除短剧的源文件吗？

不监控短剧原目录就不会删除。我刚测试了只用短剧刮削插件，删除硬链接是正常的

**Comment by LoSiTeE** [comment]
> > > > > @LoSiTeE “启用插件”开关关闭再打开
> > > > 
> > > > 
> > > > 我打算这两天重新装一下moviepilot，如果还有问题我再来反馈一下
> > > 
> > > 
> > > 有没有使用短剧自动分类插件？用这个插件时，“清理硬链接”插件会把源文件删掉
> > 
> > 
> > 🤨这样的吗？我是之前用短剧分类插件的，但是老莫名其妙出问题，导致短剧无法被自动分类。后来改成用短剧刮削插件。但是清除硬链接又无法正常工作😐
> > 请问我用短剧分类插件的话，如果清理硬链接里面没有填写对应的短剧目录，只是监控了其他目录的话，也会删除短剧的源文件吗？
> 
> 不监控短剧原目录就不会删除。我刚测试了只用短剧刮削插件，删除硬链接是正常的

那我这两天回去重装一下mp看看

**Comment by LoSiTeE** [comment]
> > > > > @LoSiTeE “启用插件”开关关闭再打开
> > > > 
> > > > 
> > > > 我打算这两天重新装一下moviepilot，如果还有问题我再来反馈一下
> > > 
> > > 
> > > 有没有使用短剧自动分类插件？用这个插件时，“清理硬链接”插件会把源文件删掉
> > 
> > 
> > 🤨这样的吗？我是之前用短剧分类插件的，但是老莫名其妙出问题，导致短剧无法被自动分类。后来改成用短剧刮削插件。但是清除硬链接又无法正常工作😐
> > 请问我用短剧分类插件的话，如果清理硬链接里面没有填写对应的短剧目录，只是监控了其他目录的话，也会删除短剧的源文件吗？
> 
> 不监控短剧原目录就不会删除。我刚测试了只用短剧刮削插件，删除硬链接是正常的

重装了mp，现在能正常删除了…[笑哭]

**Comment by DzAvril** [comment]
@LoSiTeE ok，没问题的话把 issue 关了吧
