### ISSUE TITLE
关于书写第三方插件时的一些疑问

### ISSUE THREAD

**Issue by tefuirZ** [jxxghp/MoviePilot-Plugins#213]
如题，想请教作者一点问题
我写了个mp的插件。在插件列表中正常显示，现在的问题是无法正常安装。安装显示404无法连接到仓库。这是什么原因呢？如果无法连接到仓库的话 重启mp它应该就不显示这个插件了呀 
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/63311404/6f4a313f-6efb-432b-bb5c-24703cd8be14)

下面是docker容器日志输出
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/63311404/3951efd5-4403-4319-9133-b8bf44865a91)

**Comment by eciycn** [comment]
遇到了同样的问题，请问你搞定了吗
