### ISSUE TITLE
媒体库刮削插件，刮削保存的图片建议以 *-thumb.jpg 的形式保存

### ISSUE THREAD

**Issue by zhiwei1998** [jxxghp/MoviePilot-Plugins#22]
如标题所述，在使用媒体库刮削插件，刮削缺失的元数据和图片时，会在目录里多保存一份缩略图

更新前的目录结构是
└── 狂飙 (2023)
    ├── fanart.jpg
    ├── poster.jpg
    ├── season01-poster.jpg
    ├── Season 1
    │   ├── 狂飙 S01E01.nfo
    │   ├── 狂飙 S01E01.mp4
    │   ├── 狂飙 S01E01-thumb.jpg
    │   └── season.nfo
    └── tvshow.nfo

更新后
└── 狂飙 (2023)
    ├── fanart.jpg
    ├── poster.jpg
    ├── season01-poster.jpg
    ├── Season 1
    │   ├── 狂飙 S01E01.nfo
    │   ├── 狂飙 S01E01.mp4
    │   ├── 狂飙 S01E01.jpg
    │   ├── 狂飙 S01E01-thumb.jpg
    │   └── season.nfo
    └── tvshow.nfo

更新完后会在目录里生成一张 “狂飙 S01E01.jpg” 的缩略图，原来使用Emby刮削就已经生成 “狂飙 S01E01-thumb.jpg” 缩略图了，使用完后就相等于会有两张缩略图，建议刮削保存的图片已 *-thumb.jpg 的形式保存，这样可以与Emby或Tinymediamanager等软件，刮削完后的文件格式一致了

**Comment by jxxghp** [comment]
已修复
