### ISSUE TITLE
【下载器文件同步】联动删除求助，谢谢

### ISSUE THREAD

**Issue by Leezxx** [jxxghp/MoviePilot-Plugins#243]
联动删除下载任务，是指联动删除不同下载器中的任务，还是源文件被删除会自动删除下载任务。

做种中的任务可以被同步，但是不知道怎么触发删除

**Comment by thsrite** [comment]
联动删除与【下载器文件同步】无太大关联
联动删除主要删除通过mp的转种和辅种插件关联的种子，未通过mp转种或辅种的已存在的关联种子不会通过mp联动删除。

【下载器文件同步】目的在于删除文件的时候判断种子文件是否完全被删除，完全删除的删除种子，未完全删除的暂停种子。

**Comment by Leezxx** [comment]
理解了，感谢大佬答复。
大佬，生活愉快，工作顺利！
