### ISSUE TITLE
豆瓣榜单订阅

### ISSUE THREAD

**Issue by ATMrunaway** [jxxghp/MoviePilot-Plugins#254]
MP版本1.8.5-1
豆瓣榜单订阅插件版本1.9
之前能正常获取到榜单信息并进行订阅，最近的版本更新后，只能获取到榜单，但是全部会报错，不能正常添加订阅。
![IMG_4305](https://github.com/jxxghp/MoviePilot-Plugins/assets/99494643/b3115973-7a2f-4c83-aeb8-0542bf24e7f8)

**Comment by dzbl04230302** [comment]
我也是这个问题，请问楼主解决了吗

**Comment by ATMrunaway** [comment]
> 我也是这个问题，请问楼主解决了吗

用自定义Rss订阅插件可以订阅豆瓣的，不过现在我都没用了，直接用的热门订阅那个新插件。

**Comment by jxxghp** [comment]
新版本插件巳经解决了

**Comment by ATMrunaway** [comment]
感谢大佬，大佬辛苦。

**Comment by dzbl04230302** [comment]
![微信截图_20240517214053](https://github.com/jxxghp/MoviePilot-Plugins/assets/29794974/daf53e0d-0b49-4bc4-9aa1-a89e26c3c0f9)
好像还是不行呀
