### ISSUE TITLE
站点未读消息插件无法获取站点消息

### ISSUE THREAD

**Issue by LoSiTeE** [jxxghp/MoviePilot-Plugins#257]

**Comment by LoSiTeE** [comment]
![Screenshot_20240503_102301_com kiwibrowser browser](https://github.com/jxxghp/MoviePilot-Plugins/assets/125968595/7bb2dc47-883d-40ed-8b17-97735edc45e6)
![Screenshot_20240503_102244_com kiwibrowser browser](https://github.com/jxxghp/MoviePilot-Plugins/assets/125968595/c29ef016-2802-4617-af12-a7adcae510c1)

**Comment by tlsban** [comment]
同样的问题

**Comment by thsrite** [comment]
更新插件1.9
