### ISSUE TITLE
“契约检查”插件无法获取ssd的数据

### ISSUE THREAD

**Issue by LoSiTeE** [jxxghp/MoviePilot-Plugins#259]
微信里的ssd契约检查信息是空的，没有内容

![Screenshot_20240505_111317_com tencent mm](https://github.com/jxxghp/MoviePilot-Plugins/assets/125968595/1aae542f-954d-4a98-a7d8-801af07dd22d)
![Screenshot_20240505_080835_com kiwibrowser browser_edit_145639382130900](https://github.com/jxxghp/MoviePilot-Plugins/assets/125968595/ba407cdb-da92-4971-a07e-17f769354c44)
![Screenshot_20240505_111716_com kiwibrowser browser](https://github.com/jxxghp/MoviePilot-Plugins/assets/125968595/472ee4ef-690b-4c97-8106-6191603bf664)

**Comment by DzAvril** [comment]
最新版本应该可以了
