### ISSUE TITLE
自动删种不起作用了

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot-Plugins#269]
【INFO】2024-05-07 19:42:18,933 - torrentremover - 自动删种任务 获取符合处理条件种子数 0
【INFO】2024-05-07 19:42:15,497 - torrentremover - 自动删种服务启动，立即运行一次
实际上符合条件的种子是存在的，上午还行，更新了最新版就不行了，客户端是transmission，关键词是registered，别的什么都没设置

**Comment by little6neko** [comment]
downloaderhelper中的自动删种功能也失效了，定时删除无法删种，监听原事件删种无法触发
配合媒体文件同步删除的结果：媒体库硬链接、下载目录的原始文件、历史记录中的同步记录均被删除，同时无法触发自动删种，导致TR中留下空白种子文件无效做种
