### ISSUE TITLE
moviepliot 提示获取插件失败

### ISSUE THREAD

**Issue by qq317423892** [jxxghp/MoviePilot-Plugins#272]
<html>
<body>

WARNING | 23:36:25,464 | plugin.py | 获取插件库失败：https://github.com/jxxghp/MoviePilot-Plugins
-- | -- | -- | --

</body>
</html>

这个要怎么解决哇

**Comment by qq317423892** [comment]
自动签到插件看不到 其他都可以

**Comment by cddjr** [comment]
加代理+加Github Token+设置UserAgent

**Comment by qq317423892** [comment]
> 加代理+加Github Token+设置UserAgent

谢谢大佬，我后面更新了 最新的 MP release 后好了，感谢大大
