### ISSUE TITLE
加入requestments.txt 后无法自动安装依赖

### ISSUE THREAD

**Issue by HankunYu** [jxxghp/MoviePilot-Plugins#28]
requestments.txt 放在插件目录下，但是安装插件后报错没法加载模块，应该是没有安装上去

有看到报错，不知道是否有关系。
mp  | ERROR: Pipe to stdout was broken
mp  | Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
mp  | BrokenPipeError: [Errno 32] Broken pipe

**Comment by HankunYu** [comment]
基本确定了SystemUtils.execute(f"pip install ") 这个有问题，没法安装。。。

**Comment by small-ora** [comment]
老哥，请教一下插件是怎么测试的，我开发了一个新插件，不知道怎么测试

**Comment by HankunYu** [comment]
> 老哥，请教一下插件是怎么测试的，我开发了一个新插件，不知道怎么测试

加到自己的mp直接实机跑测试。。。
