### ISSUE TITLE
【收藏洗版】在Plex上使用有问题

### ISSUE THREAD

**Issue by trott90** [jxxghp/MoviePilot-Plugins#290]
当把电影添加到watchlist以后运行报错，下面是log

DEBUG:   bestfilmversion - BestFilmVersion插件 item打印 {'ExternalUrls': [{'Name': 'TheMovieDb', 'Url': 'tmdb://823464'}]}
Job "立即运行收藏洗版 (trigger: date[2024-05-14 11:33:15 CST], next run at: 2024-05-14 11:33:15 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/bestfilmversion/__init__.py", line 451, in sync
    tmdb_id = item_info_resp.tmdbid
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'tmdbid'

**Comment by trott90** [comment]
没有报错了，但好像还是不行，我看了下，我看了下，plex里拿到的item_info_resp的值如下
{'ExternalUrls': [{'Name': 'TheMovieDb', 'Url': 'tmdb://823464'}]}

所以下面的代码拿tmdb_id的时候是拿不到的
tmdb_id = item_info_resp.get("tmdbid")

**Comment by jxxghp** [comment]
> 没有报错了，但好像还是不行，我看了下，我看了下，plex里拿到的item_info_resp的值如下 {'ExternalUrls': [{'Name': 'TheMovieDb', 'Url': 'tmdb://823464'}]}
> 
> 所以下面的代码拿tmdb_id的时候是拿不到的 tmdb_id = item_info_resp.get("tmdbid")

我没有plex，我只能爱你发的结构调了。
