### ISSUE TITLE
插件有留交互类消息推送的口子吗，想弄一个对接自己小程序做消息交互

### ISSUE THREAD

**Issue by iamckun** [jxxghp/MoviePilot-Plugins#3]

**Comment by jxxghp** [comment]
发送可以，收不行，除非你模拟已有渠道的报文发进来。

**Comment by iamckun** [comment]
> 发送可以，收不行，除非你模拟已有渠道的报文发进来。

@jxxghp 如果通过微信的报文进来回复的地方不就是微信了吗，还能通过我的渠道回我吗

**Comment by iamckun** [comment]
@jxxghp 就能不能你这边定义一套规范我们来对接这样子

**Comment by jxxghp** [comment]
补充下：插件现在是支持注册API的，可以在插件中实现一个消息接收的API，然后调用MP的已有功能来实现响应。

**Comment by iamckun** [comment]
> 补充下：插件现在是支持注册API的，可以在插件中实现一个消息接收的API，然后调用MP的已有功能来实现响应。

就模拟企业微信小程序发送请这种吗

**Comment by iamckun** [comment]
> > 补充下：插件现在是支持注册API的，可以在插件中实现一个消息接收的API，然后调用MP的已有功能来实现响应。
> 
> 就模拟企业微信小程序发送请这种吗

有什么办法可以debug嘛，主程序没得sites 没法启动哎
