### ISSUE TITLE
最近更新后的下载器助手无法执行tr相关任务

### ISSUE THREAD

**Issue by NickCN47** [jxxghp/MoviePilot-Plugins#307]
转种插件、辅种插件均能正常访问tr、正常运行，但是更新1.8及1.9后下载器助手运行时始终只运行qb相关任务，不执行tr相关任务，日志中也只有qb任务的执行记录。tr的版本为4.0.5。
设置如下：
![1](https://github.com/jxxghp/MoviePilot-Plugins/assets/38306255/d9a2c885-5101-4eb6-8fc9-0a3607204077)
![2](https://github.com/jxxghp/MoviePilot-Plugins/assets/38306255/c90dd6d4-befe-4207-a4e2-60538900a4f7)
日志如下：
![3](https://github.com/jxxghp/MoviePilot-Plugins/assets/38306255/64238ef9-f573-4816-be41-2cc46d7e803d)

**Comment by hotlcc** [comment]
设定/系统 中的“当前使用下载器”需要勾选

**Comment by hotlcc** [comment]
确认问题解决后关闭本iss
