### ISSUE TITLE
【HomePage】homepage插件为什么被删除了呢，用的很不错啊

### ISSUE THREAD

**Issue by carolcoral** [jxxghp/MoviePilot-Plugins#337]
类似这样的监控：
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/8952687/0f5be434-6082-475c-8bcb-35b609f48d86)

**Comment by jxxghp** [comment]
在t佬的仓库，不在这里
https://github.com/thsrite/MoviePilot-Plugins
