### ISSUE TITLE
下载器助手安装异常

### ISSUE THREAD

**Issue by KevinZjYang** [jxxghp/MoviePilot-Plugins#356]
具体体现为：
1、商店最新为2.7版本，安装后提示成功，实际在已安装插件里面不显示。
2、重启mp。插件显示为2.4版本，提示有更新，更新完后就又消失了。。。
下面是mp启动时候的日志，安装的2.4版本（实际我商店安装的2.7版本）
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/31529584/d6178221-e56d-4d3a-8a07-f91a304f0144)
这里我使用自动更新插件手动更新的日志。
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/31529584/9717a0a1-edc0-4c99-85d3-fab53ea557ad)

**Comment by dlovew** [comment]
同样的问题，目前就这个插件经常这样

**Comment by KevinZjYang** [comment]
1.9.3版本已修复。
