### ISSUE TITLE
【下载器助手】BT/PT标签识别不对，导致站点标签获取不到

### ISSUE THREAD

**Issue by dongjiqiang** [jxxghp/MoviePilot-Plugins#361]
qbittorrent版本是v4.3.9, 下载器助手是v2.8版本，BT/PT标签识别不对，所有种子全都是PT的，但都识别成了BT, 导致不能正确打站点标签了
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/17396054/7f6e2376-0685-455a-baba-227c2274c375)

**Comment by karte796** [comment]
所以这个是配置问题吗，你是怎么解决的

**Comment by dongjiqiang** [comment]
更新作者的v2.9版本
https://github.com/hotlcc/MoviePilot-Plugins-Third
