### ISSUE TITLE
媒体库服务器通知  配置好没有用

### ISSUE THREAD

**Issue by 907739769** [jxxghp/MoviePilot-Plugins#366]
媒体库服务器通知  配置好没有用
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/27858369/0710b5dd-29ad-495a-a9c7-3b7e712e58b1)
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/27858369/b1d2f948-0127-4ae3-8d52-e50bdb55c79a)
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/27858369/03b8d5d3-a69c-485e-ba50-d78618d7acb4)

**Comment by 907739769** [comment]
最新版的emby和mp

**Comment by AisukaYuki** [comment]
请求类型 改成 multipart/form-data

**Comment by 907739769** [comment]
> 请求类型 改成 multipart/form-data

一样的  点击测试 没有收到消息

**Comment by azsummer** [comment]
> 请求类型 改成 multipart/form-data

emby版本:[4.8.8.0]
同样没有通知,只有一条日志
处理事件：webhook.message - [<function DouBanWatching.sync_log at 0x7f2ea990c720>, <function DouBanWatching.sync_played at 0x7f2ea990c7c0>, <function MediaServerMsg.send at 0x7f2ea96a0c20>]

**Comment by AisukaYuki** [comment]
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/17586327/765c2e86-36b6-4165-a44d-e03d5cd7a4ee)
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/17586327/dba9d5b8-3220-4e59-b64d-5eed6c0bf4ba)
我的没问题。你先确保你的mp能正常收到webhook通知。
直接播放暂停看通知，测试没用。
