### ISSUE TITLE
[媒体库刮削] mp升级1.9.8之后媒体库刮削目录识别错误

### ISSUE THREAD

**Issue by dalamudx** [jxxghp/MoviePilot-Plugins#399]
mp升级1.9.8之后媒体库刮削目录识别错误
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/88395653/b3e4a386-de47-477f-ac18-a52dcfde2958)

**Comment by dalamudx** [comment]
好像是主程序的问题

**Comment by XuCcc** [comment]
同样问题 如何解决的 升级主程序吗
```bash

【INFO】2024-06-30 10:23:01,611 - libraryscraper - 媒体库 /media/repo/动漫/凡人修仙传 (2020)/ 刮削完成
【INFO】2024-06-30 10:23:01,610 - themoviedb - /media/repo/动漫/凡人修仙传 (2020)/Season 1/凡人修仙传 - S01E106 - 第 106 集.mp4 刮削完成

NotADirectoryError: [Errno 20] Not a directory: '/media/repo/动漫/凡人修仙传 (2020)/Season 1/凡人修仙传 - S01E106 - 第 106 集.mp4/season.nfo'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return io.open(self, mode, buffering, encoding, errors, newline)
  File "/usr/local/lib/python3.11/pathlib.py", line 1044, in open
         ^^^^^^^^^^^^^^^^^^^^
    with self.open(mode='wb') as f:
  File "/usr/local/lib/python3.11/pathlib.py", line 1067, in write_bytes
    file_path.write_bytes(xml_str)
  File "/app/app/modules/themoviedb/scraper.py", line 441, in __save_nfo
    self.__save_nfo(doc, season_path.joinpath("season.nfo"))
  File "/app/app/modules/themoviedb/scraper.py", line 343, in __gen_tv_season_nfo_file
    self.__gen_tv_season_nfo_file(seasoninfo=seasoninfo,
  File "/app/app/modules/themoviedb/scraper.py", line 169, in gen_scraper_files
【ERROR】2024-06-30 10:23:01,609 - scraper.py - /media/repo/动漫/凡人修仙传 (2020)/Season 1/凡人修仙传 - S01E106 - 第 106 集.mp4 刮削失败：[Errno 20] Not a directory: '/media/repo/动漫/凡人修仙传 (2020)/Season 1/凡人修仙传 - S01E106 - 第 106 集.mp4/season.nfo' - Traceback (most recent call last):
【INFO】2024-06-30 10:23:01,607 - scraper.py - 正在生成季NFO文件：凡人修仙传 - S01E106 - 第 106 集.mp4
【INFO】2024-06-30 10:23:01,603 - themoviedb - 开始刮削媒体库文件：/media/repo/动漫/凡人修仙传 (2020)/Season 1/凡人修仙传 - S01E106 - 第 106 集.mp4 ...
【INFO】2024-06-30 10:23:01,594 - themoviedb - 106449 TMDB识别结果：电视剧 凡人修仙传 (2020)
【INFO】2024-06-30 10:23:01,585 - libraryscraper - 读取到本地nfo文件的tmdbid：106449
【INFO】2024-06-30 10:23:01,583 - themoviedb - /media/repo/动漫/凡人修仙传 (2020)/Season 1/凡人修仙传 - S01E105 - 第 105 集.mp4 刮削完成

NotADirectoryError: [Errno 20] Not a directory: '/media/repo/动漫/凡人修仙传 (2020)/Season 1/凡人修仙传 - S01E105 - 第 105 集.mp4/season.nfo'
```

**Comment by dalamudx** [comment]
> 同样问题 如何解决的 升级主程序吗
> 
> ```shell
> 【INFO】2024-06-30 10:23:01,611 - libraryscraper - 媒体库 /media/repo/动漫/凡人修仙传 (2020)/ 刮削完成
> 【INFO】2024-06-30 10:23:01,610 - themoviedb - /media/repo/动漫/凡人修仙传 (2020)/Season 1/凡人修仙传 - S01E106 - 第 106 集.mp4 刮削完成
> 
> NotADirectoryError: [Errno 20] Not a directory: '/media/repo/动漫/凡人修仙传 (2020)/Season 1/凡人修仙传 - S01E106 - 第 106 集.mp4/season.nfo'
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     return io.open(self, mode, buffering, encoding, errors, newline)
>   File "/usr/local/lib/python3.11/pathlib.py", line 1044, in open
>          ^^^^^^^^^^^^^^^^^^^^
>     with self.open(mode='wb') as f:
>   File "/usr/local/lib/python3.11/pathlib.py", line 1067, in write_bytes
>     file_path.write_bytes(xml_str)
>   File "/app/app/modules/themoviedb/scraper.py", line 441, in __save_nfo
>     self.__save_nfo(doc, season_path.joinpath("season.nfo"))
>   File "/app/app/modules/themoviedb/scraper.py", line 343, in __gen_tv_season_nfo_file
>     self.__gen_tv_season_nfo_file(seasoninfo=seasoninfo,
>   File "/app/app/modules/themoviedb/scraper.py", line 169, in gen_scraper_files
> 【ERROR】2024-06-30 10:23:01,609 - scraper.py - /media/repo/动漫/凡人修仙传 (2020)/Season 1/凡人修仙传 - S01E106 - 第 106 集.mp4 刮削失败：[Errno 20] Not a directory: '/media/repo/动漫/凡人修仙传 (2020)/Season 1/凡人修仙传 - S01E106 - 第 106 集.mp4/season.nfo' - Traceback (most recent call last):
> 【INFO】2024-06-30 10:23:01,607 - scraper.py - 正在生成季NFO文件：凡人修仙传 - S01E106 - 第 106 集.mp4
> 【INFO】2024-06-30 10:23:01,603 - themoviedb - 开始刮削媒体库文件：/media/repo/动漫/凡人修仙传 (2020)/Season 1/凡人修仙传 - S01E106 - 第 106 集.mp4 ...
> 【INFO】2024-06-30 10:23:01,594 - themoviedb - 106449 TMDB识别结果：电视剧 凡人修仙传 (2020)
> 【INFO】2024-06-30 10:23:01,585 - libraryscraper - 读取到本地nfo文件的tmdbid：106449
> 【INFO】2024-06-30 10:23:01,583 - themoviedb - /media/repo/动漫/凡人修仙传 (2020)/Season 1/凡人修仙传 - S01E105 - 第 105 集.mp4 刮削完成
> 
> NotADirectoryError: [Errno 20] Not a directory: '/media/repo/动漫/凡人修仙传 (2020)/Season 1/凡人修仙传 - S01E105 - 第 105 集.mp4/season.nfo'
> ```

升级主程序，是个bug已经修复了
