### ISSUE TITLE
短剧分类插件使用异常反馈

### ISSUE THREAD

**Issue by JxiaoC** [jxxghp/MoviePilot-Plugins#404]
发现短剧分类插件v1.4使用了已经被MP删除的settings.LIBRARY_CATEGORY导致没有按照预期执行。

最开始是放了一堆`logger.info`发现只打印了`start!`，后来将打印修改为`logger.info(f"start! settings.LIBRARY_CATEGORY: {settings.LIBRARY_CATEGORY}")`发现就没有任何打印了，怀疑有问题就加了except，结果就出现了`'Settings' object has no attribute 'LIBRARY_CATEGORY'`, 查看MP的源码发现`settings`是有`LIBRARY_CATEGORY`的，但是pull最新代码过后发现的确`LIBRARY_CATEGORY`被删除了，特来反馈，希望能更新其他检测方式。
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/6435789/d9a9f563-e470-4cff-9b9f-aa85a235f635)

**Comment by JxiaoC** [comment]
后续通过注释代码的方式测试了下，除了`LIBRARY_CATEGORY`检测异常以外，其他都按预期运行，我是docker环境，尝试添LIBRARY_CATEGORY=true也没有作用。

![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/6435789/098cbb12-0213-4da9-b826-db31e1a7bcba)

**Comment by ptninja** [comment]
自动备份插件也遇到类似问题

```
自动备份定时服务 执行失败
'Settings' object has no attribute 'LIBRARY_CATEGORY'
```
