### ISSUE TITLE
站点数据统计 馒头 403 v4.0.1

### ISSUE THREAD

**Issue by Andy-Home** [jxxghp/MoviePilot-Plugins#448]
![1723797186471](https://github.com/user-attachments/assets/5d3bea98-89d0-4915-8dc1-beed095a415a)

馒头站点在站点管理测试可连通，但是数据统计时汇报403问题

**Comment by Great-old-one** [comment]
+1，好长一段时间了

**Comment by cddjr** [comment]
没有发现馒头有这个问题

**Comment by Andy-Home** [comment]
> 没有发现馒头有这个问题

你得站点是怎么配置的呢？除了api之外有什么其他设置么

**Comment by cddjr** [comment]
> > 没有发现馒头有这个问题
> 
> 你得站点是怎么配置的呢？除了api之外有什么其他设置么

我用的kp.cc的馒头域名，其余没有特殊设置。数据统计插件的版本4.0.1，你看看是不是没升级到最新导致。

**Comment by cddjr** [comment]
对了，还有一个地方需要注意的，就是你有没有设置浏览器User-Agent？ 
比如Mozilla/5.0 (Windows NT 10.0; Win64....

没有的话，就抓取你浏览器的ua，填进去

**Comment by Andy-Home** [comment]
> 对了，还有一个地方需要注意的，就是你有没有设置浏览器User-Agent？ 比如Mozilla/5.0 (Windows NT 10.0; Win64....
> 
> 没有的话，就抓取你浏览器的ua，填进去

搞定，谢谢。不知道这个影响刷流，之前是改用了API
