### ISSUE TITLE
自动转移做种插件相关问题

### ISSUE THREAD

**Issue by Lunaticzy** [jxxghp/MoviePilot-Plugins#51]
作者大大，你好。

在使用自动转移做种插件时，我遇到了一个问题。该插件在检测到qb的种子没有tracker时，只会添加fastresume文件中的第一个tracker地址，这带来了一些困扰。某些站点的种子可能包含多个tracker地址，由于网络因素，我只能连接到其中的一个特定tracker地址，而不是fastresume中的第一个。这可能导致黄种问题，希望作者大大能够修复这个问题。谢谢

https://github.com/jxxghp/MoviePilot-Plugins/blob/247fd239f45e56c241d90e9c35c66c7469661128/plugins/torrenttransfer/__init__.py#L648

**Comment by fayswing** [comment]
我也遇到了同样的问题    希望大佬修复
