### ISSUE TITLE
MP V2版本站点数据统计v1.1

### ISSUE THREAD

**Issue by nidage999** [jxxghp/MoviePilot-Plugins#530]
选择汇总数据时仪表盘有显示 但插件里面无站点数据（有时会显示一下，但持续一会就消失了） 是一片空白 选择今日数据或者所有数据时 仪表盘无显示 站点数据也是一片空白 看日志每个站点是有解析的 但没有自动运行 点一次立即运行就运行一次 多次卸载插件重装以及重装MP都没有效果

**Comment by tripewa** [comment]
等老大解决吧

**Comment by gjh5350** [comment]
我的也是同样的问题 。。。

**Comment by zengjiu** [comment]
统计的信息 不会推送今天上传下载多少到配置的消息通道了

**Comment by gjh5350** [comment]
在哪能看到统计的信息。或者别的插件之类有代替的吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zengjiu ***@***.***&gt;
发送时间: 2024年12月21日 23:57
收件人: jxxghp/MoviePilot-Plugins ***@***.***&gt;
抄送: gjh5350 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [jxxghp/MoviePilot-Plugins] MP V2版本站点数据统计v1.1 (Issue #530)





 
统计的信息 不会推送今天上传下载多少到配置的消息通道了
