### ISSUE TITLE
webhook是否未适配V2版本，不能触发系统消息，日志中也看不到消息

### ISSUE THREAD

**Issue by Dapong** [jxxghp/MoviePilot-Plugins#535]
如图
![image](https://github.com/user-attachments/assets/c485358d-f1d6-4636-8f56-ab78438552e3)
![image](https://github.com/user-attachments/assets/4d7bbec9-a78c-48b3-9fba-ffcf6d79d52d)

**Comment by wmbin** [comment]
同样问题
