### ISSUE TITLE
v2版本自动分类插件异常

### ISSUE THREAD

**Issue by hbzjwyz** [jxxghp/MoviePilot-Plugins#538]
v2版本自动分类插件异常，无法添加分类
【INFO】2024-11-07 14:07:00,465 - downloadsitetag - [DownloadSiteTag] 执行完成
【INFO】2024-11-07 14:07:00,347 - downloadsitetag - [DownloadSiteTag] 下载器 qb 分析种子信息中 ...
【INFO】2024-11-07 14:07:00,346 - downloadsitetag - [DownloadSiteTag] 按时间重新排序 qb 种子数：170
【INFO】2024-11-07 14:07:00,307 - downloadsitetag - [DownloadSiteTag] 开始扫描下载器 qb ...
【INFO】2024-11-07 14:07:00,303 - downloadsitetag - [DownloadSiteTag] 开始执行 ...
v1版本可以正常运行
【INFO】2024-11-07 14:10:17,233 - downloadsitetag - [DownloadSiteTag] 执行完成
【INFO】2024-11-07 14:10:17,232 - downloadsitetag - [DownloadSiteTag] 开始扫描下载器 transmission ...
【WARNING】2024-11-07 14:10:17,232 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: e45a5af8820df8dd0350ad11539327834685cd7c    分类: 剧集
【WARNING】2024-11-07 14:10:17,226 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: 89680dceaa5043b38b90a6c251db44f8f2983cf2    分类: 剧集
【WARNING】2024-11-07 14:10:17,220 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: 00d908ab5a4195f499fdcb438b59db77a8c57835    分类: 剧集
【WARNING】2024-11-07 14:10:17,214 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: af8d7786f27b27fd0a8b21ebe829e5bc4cc6767e    分类: 剧集
【WARNING】2024-11-07 14:10:17,207 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: f4673267cc1d1b7d0381d97fcdd2b937876b3b0f    分类: 剧集
【WARNING】2024-11-07 14:10:16,817 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: 9a95775ef7875b701a2a8846d53e882fc0d561d1    分类: 电影
【WARNING】2024-11-07 14:10:16,812 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: cd31e0b5910d8cd53eb974091a4abe55f37d0a3a    分类: 剧集
【WARNING】2024-11-07 14:10:16,526 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: 64a597d85c2d6c144975609769aa597917599f9e    分类: 电影
【WARNING】2024-11-07 14:10:16,524 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: aa0068d82d6f4e2c281c941fb955057b544caac3    分类: 剧集
【WARNING】2024-11-07 14:10:16,129 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: 5dceadc4bce5cd317b30c3a5cc552a75840a77e3    分类: 剧集
【WARNING】2024-11-07 14:10:16,122 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: dcfe652596be6d7cd940ddbc209e77e23bb719ce    分类: 剧集
【WARNING】2024-11-07 14:10:16,116 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: 5fc6e8eb4c854d36a5cc342c1a4f57fc945f9987    分类: 电影
【WARNING】2024-11-07 14:10:16,113 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: 9e949f7ce60e97c4ba2a839367f96b8d81ecb150    分类: 电影
【WARNING】2024-11-07 14:10:16,110 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: c198e0dec25330786fa6b6ed38845656217044da    分类: 电影
【WARNING】2024-11-07 14:10:16,107 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: f21e80c5f99d6298b39a1115faef4dcf6a6e472d    分类: 剧集
【WARNING】2024-11-07 14:10:15,822 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: ff19ed85786702406463de288e67ff458af94f0b    分类: 电影
【WARNING】2024-11-07 14:10:15,819 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: 258c6375c9bb4f4287c1e4cfcf08b17e1723f68b    分类: 剧集
【WARNING】2024-11-07 14:10:14,928 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: 97dd08930ead549deb77c194c41ec9af269f6b3a    分类: 电影
【WARNING】2024-11-07 14:10:14,925 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: 7b4833d0363a4ff8c79c3af9127b2c075183fc03    分类: 电影
【WARNING】2024-11-07 14:10:14,923 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: 2ef7b205a14d308544f455fe9325d6d5a0fd7359    分类: 电影
【WARNING】2024-11-07 14:10:14,920 - downloadsitetag - [DownloadSiteTag] 下载器: qbittorrent 种子id: 6d9e3dcc90e698e10935ec11f8ba32f75616b0e6    分类: 电影
【INFO】2024-11-07 14:10:14,725 - downloadsitetag - [DownloadSiteTag] 下载器 qbittorrent 分析种子信息中 ...
【INFO】2024-11-07 14:10:14,724 - downloadsitetag - [DownloadSiteTag] 按时间重新排序 qbittorrent 种子数：170
【INFO】2024-11-07 14:10:14,682 - downloadsitetag - [DownloadSiteTag] 开始扫描下载器 qbittorrent ...
【INFO】2024-11-07 14:10:14,678 - downloadsitetag - [DownloadSiteTag] 开始执行 ...

**Comment by cikezhu** [comment]
分类插件依赖于下载历史记录信息。
当切换至V2版本时，因该版本必须全新部署，数据库不兼容。所以无法获取到种子的历史下载信息，那么也就无法进行分类等操作
