### ISSUE TITLE
MPv2豆瓣想看插件升级到1.9之后无法正常使用

### ISSUE THREAD

**Issue by ThierryCheng** [jxxghp/MoviePilot-Plugins#543]
TypeError: RssHelper.parse() got an unexpected keyword argument 'headers'
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    results = self.rsshelper.parse(url, headers={
  File "/app/app/plugins/doubansync/__init__.py", line 512, in sync
    job["func"](*args, **kwargs)
  File "/app/app/scheduler.py", line 387, in start
【ERROR】2024-11-08 09:00:00,120 - scheduler.py - 定时任务 豆瓣想看同步服务 执行失败：RssHelper.parse() got an unexpected keyword argument 'headers' - Traceback (most recent call last):

**Comment by alifather** [comment]
v1.9.17也无法使用
