### ISSUE TITLE
V2版本 自动删种插件运行异常

### ISSUE THREAD

**Issue by felix-klk** [jxxghp/MoviePilot-Plugins#552]
![image](https://github.com/user-attachments/assets/b7296f21-27b7-4c34-96cc-7d1506963573)
出现这个情况 还有显示没获取到种子 但是事实上qb是存在种子的 全部配置都是旧版mp时候直接粘贴过来的
![image](https://github.com/user-attachments/assets/2a639d5c-3262-4131-b591-64e1942cd1e7)

**Comment by dongjiqiang** [comment]
我也遇到了同样的问题

**Comment by dongjiqiang** [comment]
![微信截图_20241114214124](https://github.com/user-attachments/assets/79ee8584-81ca-4658-964a-07a4d283543d)
![image](https://github.com/user-attachments/assets/841bd42a-747f-448c-9d23-0657e496012f)
应该是这里的判断有问题, 导致进入了tr的判断逻辑, qb的种子没有hashString字段, 就报错了

**Comment by dongjiqiang** [comment]
![微信截图_20241114214124](https://github.com/user-attachments/assets/6732a77b-67b7-494c-ac72-026c97d20abe)
![image](https://github.com/user-attachments/assets/30ab3981-ebd4-445b-a7b3-46000f389543)
应该是这里的判断有问题, 导致进入了tr的判断逻辑, qb的种子没有hashString字段, 就报错了额
