### ISSUE TITLE
IYUU自动辅种插件显示用户未绑定推荐站点，但是我已经在IYUU绑定插件里绑定成功了。

### ISSUE THREAD

**Issue by wanicca** [jxxghp/MoviePilot-Plugins#554]
IYUU自动辅种无法运行，提示
![image](https://github.com/user-attachments/assets/b98587ca-104d-428d-bb10-2e1b4303ad76)
但是我已经在IYUU站点绑定那个插件里绑定成功了
![image](https://github.com/user-attachments/assets/6ecee826-9a4a-41e7-a970-798f46ca4e07)

**Comment by wanicca** [comment]
将旧公众号token迁移顶掉换成旧公众号token后，莫名其妙解决了。

**Comment by alfredoo7** [comment]
和你一样的问题，这个是通用做法吗
