### ISSUE TITLE
v2webhooks同emby通知不生效

### ISSUE THREAD

**Issue by HEITU515** [jxxghp/MoviePilot-Plugins#561]
mp升级v2后，webhooks同emby通知不生效，在emby中发送测试通知，日志中反应如下
2024/11/17 23:27:11 | stdout | INFO:     192.168.50.220:0 - "POST /api/v1/message/?token=************ HTTP/1.1" 200 OK
而媒体库服务器通知的日志中则为一片空白，该如何解决？
v1版本中使用则正常。

**Comment by gldl137** [comment]
解决没

**Comment by 20191864231** [comment]
同样问题
