### ISSUE TITLE
V2版本 刷流组件 自动购买魔力付费的种子

### ISSUE THREAD

**Issue by billxc** [jxxghp/MoviePilot-Plugins#564]
没有看到有规则可以避免。
相关站点rousi
相关种子：/details.php?id=42279&hit=1

**Comment by mituzhe** [comment]
我也遇到这个问题，所以我不刷流他了

**Comment by EntroWang** [comment]
> 没有看到有规则可以避免。 相关站点rousi 相关种子：/details.php?id=42279&hit=1

RSS订阅里面是不是可以设置呀

**Comment by billxc** [comment]
> > 没有看到有规则可以避免。 相关站点rousi 相关种子：/details.php?id=42279&hit=1
> 
> RSS订阅里面是不是可以设置呀

没有用RSS订阅，就是直接自动拉FREE的种子，然后开始刷，
然后有些种子被设置了魔力付费，但是还是被算到了FREE里面。
怕再出问题，目前我也不在刷rousi

**Comment by billxc** [comment]
rousi 已经针对这个问题发布了公告，恶意发布魔力种子的现象应该会消失，关掉issue了
