### ISSUE TITLE
清理硬链接插件无效

### ISSUE THREAD

**Issue by LoSiTeE** [jxxghp/MoviePilot-Plugins#60]
我看了一下插件的文字说明，我理解的是填写目的目录即可。然后插件会监控目的目录，一旦删除文件就会同步删除其硬链接。

但是我删除目的目录的文件时，日志中是没有任何反应的，没有一条关于removelink的日志。所以我也尝试了将源目录也填写至插件。像是这样：
![%7B800788AC-A01A-4239-88C5-9DD7932FFB50%7D](https://github.com/jxxghp/MoviePilot-Plugins/assets/125968595/47a0f847-3f87-4f6e-bd61-fbd7ed2f5cab)

很不幸，当我完成设置后，插件依旧无效。

接下来，我尝试删除源目录文件，看是否会触发目的目录文件的删除。当我删除源目录的文件时，日志会报：“removelink 检测到XXXXX文件删除”，“更新文件列表完成，共计xxxxx个文件，耗时：xxxxxxx秒”。这跟删除目的目录的文件相比好一些，至少日志有了removelink的反应。但是然后就没有然后了……查看目的目录中的硬链接文件也没有被删除。

所以我想恳请作者看下这个插件是否有bug，还是我的设置有误。谢谢。

**Comment by NikoYomi** [comment]
+1，我也是这个问题，我刚开始以为权限问题，但是给了管理员权限也不行。

**Comment by jxxghp** [comment]
@DzAvril

**Comment by NikoYomi** [comment]
> @LoSiTeE @NikoYomi 更更新了一个版本，MP下个版本应该能合入。如有问题欢迎继续提issue

大佬辛苦啦！！
尝试了1.1版本，好消息是能联动删除硬链接了！
坏消息是同样的文件在删除后，再添加，他会自动删除源文件和硬链接文件。qaq！

**Comment by DzAvril** [comment]
> > @LoSiTeE @NikoYomi 更更新了一个版本，MP下个版本应该能合入。如有问题欢迎继续提issue
> 
> 大佬辛苦啦！！ 尝试了1.1版本，好消息是能联动删除硬链接了！ 坏消息是同样的文件在删除后，再添加，他会自动删除源文件和硬链接文件。qaq！

感谢发现bug
我没复现你描述的这个场景。可以再详细点说一下复现流程吗？

**Comment by NikoYomi** [comment]
> > > @LoSiTeE @NikoYomi 更更新了一个版本，MP下个版本应该能合入。如有问题欢迎继续提issue
> > 
> > 
> > 大佬辛苦啦！！ 尝试了1.1版本，好消息是能联动删除硬链接了！ 坏消息是同样的文件在删除后，再添加，他会自动删除源文件和硬链接文件。qaq！
> 
> 感谢发现bug 我没复现你描述的这个场景。可以再详细点说一下复现流程吗？

我在源目录复制文件：泰坦陨落.jpg，通知显示硬链接成功。
如图：
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/120245220/ce75509b-266d-40aa-b8fd-fd1135ba2181)

接着我删除该文件。此时删除硬链接起效，删除了硬链接文件。
如图：
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/120245220/994aa34f-4a31-4801-ab43-44944eb1d833)

以上步骤暂未出现问题。
————————————————————————————————————————————————————

1.1版本的问题是
我再一次往源目录添加一模一样的文件：泰坦陨落.jpg
他会硬链接完成后，并立即删除该文件。
这是1.1版本存在的问题。
————————————————————————————————————————————————————

今天发现自动更新1.2版本了。
此时的问题是：
我再一次往源目录添加一模一样的文件：泰坦陨落.jpg
他不会立即删除该文件了，但是同样的，我手动删除原目录里的文件，它也不起作用去删除硬连接文件。
总的来说，此时的问题是他只会删除一次同名或者同一个文件。

**Comment by DzAvril** [comment]
> > > > @LoSiTeE @NikoYomi 更更新了一个版本，MP下个版本应该能合入。如有问题欢迎继续提issue
> > > 
> > > 
> > > 大佬辛苦啦！！ 尝试了1.1版本，好消息是能联动删除硬链接了！ 坏消息是同样的文件在删除后，再添加，他会自动删除源文件和硬链接文件。qaq！
> > 
> > 
> > 感谢发现bug 我没复现你描述的这个场景。可以再详细点说一下复现流程吗？
> 
> 我在源目录复制文件：泰坦陨落.jpg，通知显示硬链接成功。 如图： ![image](https://private-user-images.githubusercontent.com/120245220/307639931-ce75509b-266d-40aa-b8fd-fd1135ba2181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjE0NjksIm5iZiI6MTcwODk2MTE2OSwicGF0aCI6Ii8xMjAyNDUyMjAvMzA3NjM5OTMxLWNlNzU1MDliLTI2NmQtNDBhYS1iOGZkLWZkMTEzNWJhMjE4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxNTI2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTBjYWQ3MDFlMmFmODdkOTMzZjdkNWQzODNkYmJkZjU5MGY4YzY0ZDU2YmI4ZTJhYWExMTM0NDc0YzQxY2JiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XKiHKq0Oib6kmz2AehjUAV28c32hzYpvmenPtjph2wY)
> 
> 接着我删除该文件。此时删除硬链接起效，删除了硬链接文件。 如图： ![image](https://private-user-images.githubusercontent.com/120245220/307640061-994aa34f-4a31-4801-ab43-44944eb1d833.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjE0NjksIm5iZiI6MTcwODk2MTE2OSwicGF0aCI6Ii8xMjAyNDUyMjAvMzA3NjQwMDYxLTk5NGFhMzRmLTRhMzEtNDgwMS1hYjQzLTQ0OTQ0ZWIxZDgzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxNTI2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDlhYzIzNGIwYjFhOWVkNzBhYjg0OWY1MzFjM2Y0YjBkNjYzMjcwNjJjYjdmYzNhNTJhMjk4MGE2MDFiMzY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PQocTj2fwCuXaMaC5eucbObWp2UcPZfWX0oDybl-QvY)
> 
> 以上步骤暂未出现问题。 ————————————————————————————————————————————————————
> 
> 1.1版本的问题是 我再一次往源目录添加一模一样的文件：泰坦陨落.jpg 他会硬链接完成后，并立即删除该文件。 这是1.1版本存在的问题。 ————————————————————————————————————————————————————
> 
> 今天发现自动更新1.2版本了。 此时的问题是： 我再一次往源目录添加一模一样的文件：泰坦陨落.jpg 他不会立即删除该文件了，但是同样的，我手动删除原目录里的文件，它也不起作用去删除硬连接文件。 总的来说，此时的问题是他只会删除一次同名或者同一个文件。

确认了一下，是因为你用的实时硬链接插件有个配置项“最小文件大小”，小于这个值就直接复制不会硬链接。你测试用的图片估计是用的复制不是硬链接。你可以用大一点的视频文件测试看看
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/18597737/7f9914ce-1488-4c3e-af2a-6f39bd43d29d)

**Comment by LoSiTeE** [comment]
> @LoSiTeE @NikoYomi 更更新了一个版本，MP下个版本应该能合入。如有问题欢迎继续提issue

你好，刚看到你的回复。我看了下还是有些问题。昨天是成功触发硬链接删除的，今天又失效了，目前在重启MP测试中。

**Comment by LoSiTeE** [comment]
> > @LoSiTeE @NikoYomi 更更新了一个版本，MP下个版本应该能合入。如有问题欢迎继续提issue
> 
> 大佬辛苦啦！！ 尝试了1.1版本，好消息是能联动删除硬链接了！ 坏消息是同样的文件在删除后，再添加，他会自动删除源文件和硬链接文件。qaq！

你好，请问你的插件正常了吗？我这边还是无法删除

**Comment by LoSiTeE** [comment]
> @LoSiTeE @NikoYomi 更更新了一个版本，MP下个版本应该能合入。如有问题欢迎继续提issue

你好，目前插件版本是1.5，还是无法触发删除。比较离谱的是，前两天删除是正常的，这两天又不好使了。目前测试的情况是无论怎样都不会触发removelink，日志中毫无反应。请问新插件的配置方法是否和我在issue截图中的一样？

**Comment by NikoYomi** [comment]
> > @LoSiTeE @NikoYomi 更更新了一个版本，MP下个版本应该能合入。如有问题欢迎继续提issue
> 
> 你好，目前插件版本是1.5，还是无法触发删除。比较离谱的是，前两天删除是正常的，这两天又不好使了。目前测试的情况是无论怎样都不会触发removelink，日志中毫无反应。请问新插件的配置方法是否和我在issue截图中的一样？

不行，我已经换回NT了，这个实时硬链接插件估计也有问题，我发现硬链接的文件有时候全是复制的，而不是硬链接，导致磁盘都满了。联动删除的插件存在问题估计也与它有关系。

**Comment by DzAvril** [comment]
> > @LoSiTeE @NikoYomi 更更新了一个版本，MP下个版本应该能合入。如有问题欢迎继续提issue
> 
> 你好，刚看到你的回复。我看了下还是有些问题。昨天是成功触发硬链接删除的，今天又失效了，目前在重启MP测试中。

如果可以ssh登录的话，手动测试下创建硬链接再删除看能不能联动删除或者`ls -i xxx`看一下inode是否一样以确认是硬链接文件。像NikoYomi说的，有可能是实时硬链接插件复制了文件而不是硬链接。

**Comment by LoSiTeE** [comment]
> > > @LoSiTeE @NikoYomi 更更新了一个版本，MP下个版本应该能合入。如有问题欢迎继续提issue
> > 
> > 
> > 你好，刚看到你的回复。我看了下还是有些问题。昨天是成功触发硬链接删除的，今天又失效了，目前在重启MP测试中。
> 
> 如果可以ssh登录的话，手动测试下创建硬链接再删除看能不能联动删除或者`ls -i xxx`看一下inode是否一样以确认是硬链接文件。像NikoYomi说的，有可能是实时硬链接插件复制了文件而不是硬链接。

![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/125968595/4f187b2f-e4bd-4906-ae4d-53a7e9f5c6ba)
查看了，是不一样的。这是复制的？

我使用mp的“实时硬链接”插件进行硬链接，设置如下
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/125968595/7e2440df-1268-4460-acca-56ab4085e279)

最小文件处写的是10240KB，源文件大小为567225KB，为何会被复制呢？

**Comment by DzAvril** [comment]
> > > > @LoSiTeE @NikoYomi 更更新了一个版本，MP下个版本应该能合入。如有问题欢迎继续提issue
> > > 
> > > 
> > > 你好，刚看到你的回复。我看了下还是有些问题。昨天是成功触发硬链接删除的，今天又失效了，目前在重启MP测试中。
> > 
> > 
> > 如果可以ssh登录的话，手动测试下创建硬链接再删除看能不能联动删除或者`ls -i xxx`看一下inode是否一样以确认是硬链接文件。像NikoYomi说的，有可能是实时硬链接插件复制了文件而不是硬链接。
> 
> ![image](https://private-user-images.githubusercontent.com/125968595/309665586-4f187b2f-e4bd-4906-ae4d-53a7e9f5c6ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1Mzc2OTQsIm5iZiI6MTcwOTUzNzM5NCwicGF0aCI6Ii8xMjU5Njg1OTUvMzA5NjY1NTg2LTRmMTg3YjJmLWU0YmQtNDkwNi1hZTRkLTUzYTdlOWY1YzZiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwNzI5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDA0OGY2MDZlYjYxNjFlY2YwYTgwNjQ3ZjI3MzhjOTZhYTQ3NGY0ODEzODhkOTIxODNmYmYzNjNhZTNkZDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GvcY89mseH__r_r9bWCgWn2ownk9q8DKGXcVXwcw5Mg) 查看了，是不一样的。这是复制的？
> 
> 我使用mp的“实时硬链接”插件进行硬链接，设置如下 ![image](https://private-user-images.githubusercontent.com/125968595/309666008-7e2440df-1268-4460-acca-56ab4085e279.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1Mzc2OTQsIm5iZiI6MTcwOTUzNzM5NCwicGF0aCI6Ii8xMjU5Njg1OTUvMzA5NjY2MDA4LTdlMjQ0MGRmLTEyNjgtNDQ2MC1hY2NhLTU2YWI0MDg1ZTI3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwNzI5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjBlYTU5YzIzZTY3NTZlY2IxNDFiOGY1ZGVlZDY2YzBiNGIyZmU0ODJjNDgzOWIzYjdlNTZmZWFlOTM2MGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1KTCcXI3rKFqX-N2d6-V2WQwzNPPXjVej6WM4UDtD3c)
> 
> 最小文件处写的是10240KB，源文件大小为567225KB，为何会被复制呢？

那就是复制的。至于为什么被复制要问实时硬链接的作者了

**Comment by LoSiTeE** [comment]
> > > > > @LoSiTeE @NikoYomi 更更新了一个版本，MP下个版本应该能合入。如有问题欢迎继续提issue
> > > > 
> > > > 
> > > > 你好，刚看到你的回复。我看了下还是有些问题。昨天是成功触发硬链接删除的，今天又失效了，目前在重启MP测试中。
> > > 
> > > 
> > > 如果可以ssh登录的话，手动测试下创建硬链接再删除看能不能联动删除或者`ls -i xxx`看一下inode是否一样以确认是硬链接文件。像NikoYomi说的，有可能是实时硬链接插件复制了文件而不是硬链接。
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/125968595/309665586-4f187b2f-e4bd-4906-ae4d-53a7e9f5c6ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1Mzc2OTQsIm5iZiI6MTcwOTUzNzM5NCwicGF0aCI6Ii8xMjU5Njg1OTUvMzA5NjY1NTg2LTRmMTg3YjJmLWU0YmQtNDkwNi1hZTRkLTUzYTdlOWY1YzZiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwNzI5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDA0OGY2MDZlYjYxNjFlY2YwYTgwNjQ3ZjI3MzhjOTZhYTQ3NGY0ODEzODhkOTIxODNmYmYzNjNhZTNkZDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GvcY89mseH__r_r9bWCgWn2ownk9q8DKGXcVXwcw5Mg) 查看了，是不一样的。这是复制的？
> > 我使用mp的“实时硬链接”插件进行硬链接，设置如下 ![image](https://private-user-images.githubusercontent.com/125968595/309666008-7e2440df-1268-4460-acca-56ab4085e279.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1Mzc2OTQsIm5iZiI6MTcwOTUzNzM5NCwicGF0aCI6Ii8xMjU5Njg1OTUvMzA5NjY2MDA4LTdlMjQ0MGRmLTEyNjgtNDQ2MC1hY2NhLTU2YWI0MDg1ZTI3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwNzI5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjBlYTU5YzIzZTY3NTZlY2IxNDFiOGY1ZGVlZDY2YzBiNGIyZmU0ODJjNDgzOWIzYjdlNTZmZWFlOTM2MGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1KTCcXI3rKFqX-N2d6-V2WQwzNPPXjVej6WM4UDtD3c)
> > 最小文件处写的是10240KB，源文件大小为567225KB，为何会被复制呢？
> 
> 那就是复制的。至于为什么被复制要问实时硬链接的作者了

好的，感谢

**Comment by cng10001** [comment]
@DzAvril 大佬 可以帮忙看看为什么插件启动不了吗？
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/115156545/104e9242-70c7-48e6-b9f7-0a6bd4944ea5)
_**我是群晖7.1系统docker**_

**Comment by DzAvril** [comment]
> @DzAvril 大佬 可以帮忙看看为什么插件启动不了吗？ ![image](https://private-user-images.githubusercontent.com/115156545/310776096-104e9242-70c7-48e6-b9f7-0a6bd4944ea5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTU0NDYsIm5iZiI6MTcwOTc5NTE0NiwicGF0aCI6Ii8xMTUxNTY1NDUvMzEwNzc2MDk2LTEwNGU5MjQyLTcwYzctNDhlNi1iOWY3LTBhNmJkNDk0NGVhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwNzA1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTA0YTJiZTdmYWZkYTgxNmYwYzI1MGY3MGQ2NjM3OWI0ZWI1OWI2NTk4ZTM0OTA5ZGEyODhhMmY4OThlZThkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eVKAR2EW71x-5tiOnPeBLRnNAPUw0jgZS3UDSO_oEAw) _**我是群晖7.1系统docker**_

应该是路径不对，确认你监控的路径在MP的docker里是可见的。简单的验证方法是ssh登录到MP的docker里，能不能cd /videopt

**Comment by cng10001** [comment]
> > @DzAvril 大佬 可以帮忙看看为什么插件启动不了吗？ ![image](https://private-user-images.githubusercontent.com/115156545/310776096-104e9242-70c7-48e6-b9f7-0a6bd4944ea5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTU0NDYsIm5iZiI6MTcwOTc5NTE0NiwicGF0aCI6Ii8xMTUxNTY1NDUvMzEwNzc2MDk2LTEwNGU5MjQyLTcwYzctNDhlNi1iOWY3LTBhNmJkNDk0NGVhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwNzA1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTA0YTJiZTdmYWZkYTgxNmYwYzI1MGY3MGQ2NjM3OWI0ZWI1OWI2NTk4ZTM0OTA5ZGEyODhhMmY4OThlZThkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eVKAR2EW71x-5tiOnPeBLRnNAPUw0jgZS3UDSO_oEAw) _**我是群晖7.1系统docker**_
> 
> 应该是路径不对，确认你监控的路径在MP的docker里是可见的。简单的验证方法是ssh登录到MP的docker里，能不能cd /videopt

![Screenshot_2024-03-07-16-24-12-473_org telegram messenger-edit](https://github.com/jxxghp/MoviePilot-Plugins/assets/115156545/6b844ede-b56c-425c-ad6e-5e24f1ea6972)
额，加了nt wiki上的这个代码好像好了
