### ISSUE TITLE
iyuu插件辅种馒头不成功

### ISSUE THREAD

**Issue by whhphd** [jxxghp/MoviePilot-Plugins#8]
iyuu 插件辅种馒头不成功，其他站点都可以辅上，就是馒头不行，用 iyuu原版手动操作就可以辅上
清空缓存后运行，查看日志，全部显示为：当前站点不在选择的辅种站点范围，跳过 ...   或者：已在下载器中，跳过 ...
怀疑是否为馒头新旧域名导致self.iyuuhelper.get_torrent_url和self._sites不一致？

>  if self._sites and site_info.get('id') not in self._sites:
            logger.info("当前站点不在选择的辅种站点范围，跳过 ...")
            return False

**Comment by whhphd** [comment]
![0eb4bc8fa2d3b9013a9515d384d1716](https://github.com/jxxghp/MoviePilot-Plugins/assets/5513043/d3f25e2e-6f19-42c4-a2f9-5d2ca2116d23)
tg群搜索到有人反映同样的问题

**Comment by TaoRone** [comment]
馒头新版后，有个问题：
IYUU辅种报错：
INFO:    iyuuautoseed - 添加下载任务：https://xp.m-team.io/api/torrent/genDlToken?https=1 ...
ERROR:   qbittorrent.py - 添加种子出错：错误：'torrent__0' 不是一个有效的 torrent 文件。

**Comment by shenliyao** [comment]
我也是这个问题
