### ISSUE TITLE
“实时硬链接”插件运行时是复制文件，而不是给文件做硬链接

### ISSUE THREAD

**Issue by LoSiTeE** [jxxghp/MoviePilot-Plugins#82]
“实时硬链接”插件运行时貌似是复制文件，而不是给文件做硬链接。
SSH查看了文件的innode如下：
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/125968595/aa33d2f0-9426-4885-b660-b5030048039a)
“实时硬链接”设置如下：
![image](https://github.com/jxxghp/MoviePilot-Plugins/assets/125968595/68da88ea-0169-4d4e-bfbb-090135986c12)
源文件大小为567225KB

**Comment by jxxghp** [comment]
v1.4 已修复
