### ISSUE TITLE
关于插件命令的疑问

### ISSUE THREAD

**Issue by dandkong** [jxxghp/MoviePilot-Plugins#9]
@staticmethod
    def get_command() -> List[Dict[str, Any]]:
        """
        定义远程控制命令
        :return: 命令关键字、事件、描述、附带数据
        """
        return [{
            "cmd": "/site_signin",
            "event": EventType.PluginAction,
            "desc": "站点签到",
            "category": "站点",
            "data": {
                "action": "site_signin"
            }
        }]

示例插件中的注册命令函数是发送一个事件，然后自己再监听
但我在开发第三方插件的时候不能新增一个EventType，有什么办法吗

**Comment by jxxghp** [comment]
@dandkong 复用PluginAction，通过data.action来判断响应，可以参考官方插件库的其他插件

**Comment by dandkong** [comment]
> @dandkong 复用PluginAction，通过data.action来判断响应，可以参考官方插件库的其他插件

好的我研究下
